### ISSUE TITLE
Unable to delete a sub-group

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#101]
Mark, as discussed I've been asked by PCO to delete a duplicate sub-group within the PM's Youth Council but it's not working. I believe it's because it has members and/or content. I'd remove the members/content but don't want the members to get a notification of this action.

The title of the sub-group is: [TO DELETE (DUPLICATE)] (https://gccollab.ca/groups/profile/6763/to-delete-duplicate)

**Comment by sdkibb** [comment]
Do we know if this is an issue with GCconnex?

**Comment by ToferC** [comment]
Shouldn't be an issue deleting a group.

**Comment by markwooff** [comment]
Just tested this on dev, it seems that the code is set up to give the admin an infinite loop asking if "they are sure" they want to delete the group unless the # of members is set to `1` (i.e. only the creator left, all other members have been removed). You will need to remove the members from that sub-group and then you should be able to delete the sub-group.

@JOutram77 we had discussed doing this before but were worried about notifications. I can confirm that no notifications are sent when an admin removes a user from a group.
