### ISSUE TITLE
Create filtered home page for various topics

### ISSUE THREAD

**Issue by markwooff** [gctools-outilsgc/gccollab#103]
As discussed last Friday, will be creating a different version of the home page to display filtered versions of the Newsfeed, Wire, Image carousel, etc.

**Comment by markwooff** [comment]
Functionality was built with commit a619523dd94cbaab47aec36ea419f3afaf8e045a and is just under review from the requester.

A new plugin was built to fulfill this request that can be shared between GCconnex and GCcollab to create new landing pages that are widget-based and completely customizable (see screenshot below):

![image](https://cloud.githubusercontent.com/assets/5591488/24473696/1abadf60-1498-11e7-9dc0-b2110ed6fcfb.png)

The admin panel for the plugin will allow you to set a page title (EN & FR) and URL for your new landing page. See: https://dev.gccollab.ca/government-gouvernement

**Comment by sdkibb** [comment]
Nicely done. This will be a good addition to both tools.

**Comment by ToferC** [comment]
Looks very cool, @markwooff ! 

Would it be possible to set up the filters by certain tags with AND/OR chaining?  That way we could quickly set up a group of tags related to a community and as new groups, blogs, etc. are created they would be added automatically, if they match our criteria.

Thoughts?

**Comment by markwooff** [comment]
@ToferC I can definitely build that in! Agreed that it would be a handy feature to have so that an admin can go in and add/edit/remove tags as they see fit without having the overhead of development time.

**Comment by markwooff** [comment]
Admin interface has been enhanced to include tag logic:

![image](https://cloud.githubusercontent.com/assets/5591488/24504252/898d8ca4-1523-11e7-94a0-d6f6890aaa55.png)

**Comment by markwooff** [comment]
New plugin was created & now being used. A "one feed" version of this can be built if requested.

**Comment by markwooff** [comment]
Re-opening issue with wireframe for new design:

![image](https://cloud.githubusercontent.com/assets/5591488/24876726/be1ddf5c-1dfa-11e7-9196-56a78460ca75.png)

**Comment by markwooff** [comment]
New version of Community page is now up on dev at https://dev.gccollab.ca/gov21-gouv21 using a one-feed column on the left displaying all entity types (Blog, Discussions, Events) and a Wire Feed on the right. Still need to work on nav menu items.

I've used the following relevant tags for this **Government in the 21st Century** page: `Public Sector, Government, Innovation, Digital Government, Government 2.0, GoC, Government of Canada`

Also attaching a summary & count of all tags used in GCcollab so we can determine which tags would be best to use when creating additional pages.
[GCcollab Tags.xlsx](https://github.com/gctools-outilsgc/gccollab/files/919896/GCcollab.Tags.xlsx)

**Comment by ToferC** [comment]
Looks awesome!

**Comment by markwooff** [comment]
Need to add the "streaming" feature to the communities plugin. Working on this for this sprint cycle.

**Comment by markwooff** [comment]
Streaming functionality has been added with aab49aa975d819be5cbd889e9c0bc61350562840
