### ISSUE TITLE
Colleague Suggestions

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#104]
When someone appears in your colleague suggestions and then you add them (send a request), I think that they should be either removed as a suggestion or at least indicated that you have already sent a request to them.

**Comment by ToferC** [comment]
We should also include the ability to "pass" on suggestions.

**Comment by markwooff** [comment]
Might be useful to include these features as part of https://github.com/gctools-outilsgc/gcconnex/issues/418

**Comment by sdkibb** [comment]
This should be GCConnex first.
