### ISSUE TITLE
Remember previous form-fills in registration form

### ISSUE THREAD

**Issue by patcon** [gctools-outilsgc/gccollab#106]
Woo! When fields don't validate and form submission fails, the form currently doesn't remember previous state. Normally it is just the password field that is stateless.

I think most users would expect the fields and drop-downs to remain. Since there are quite a few forms fields, this feels like not insignificant friction for the the ever-important registration process, which is pretty important as the first interaction :)

https://imgur.com/59sAPSJ

**Comment by markwooff** [comment]
Thanks @patcon, I agree that this would be an annoyance to users that need to fill out the registration form again. This will be built into the registration process along with some wording that will be addressed in issue #107.

**Comment by markwooff** [comment]
Issue has been addressed with latest commit e3e136a582cebc45299a56b21b1e92680554a69d, will be on the live version of GCcollab soon.
