### ISSUE TITLE
Clarify which email addresses are not accepted for registation

### ISSUE THREAD

**Issue by patcon** [gctools-outilsgc/gccollab#107]
I just tried to sign up, and after a handfull of attempts, I realized that either the site isn't open to the public yet, or for some reason gmail is not accepted. Would be great to offer clarity on that, to help people have the best experience possible, even if it is pre-launch :)

(For example, I might have excitedly sent the login link to a bunch of folks who I knew would be really into this, and then we would all have a confusing first encounter, which would be unfortunate...! <3 )

This goes without saying, but I'm grateful that this project is being worked on. Thanks!

https://imgur.com/59sAPSJ

**Comment by ToferC** [comment]
Thanks, @patcon for the heads-up and your patience with us. We'll get some explanatory language to guide folks and provide better context up ASAP.

**Comment by markwooff** [comment]
@JOutram77 let's take a look at this when you have a chance.

**Comment by ToferC** [comment]
I've asked Gen to draft new language. Pls. Touch base. Thanks!

**Comment by LemieuxGen** [comment]
@markwooff Changes to the text for the login and registration text are done. I'll send them to you by email.

**Comment by markwooff** [comment]
@LemieuxGen thank you, I'll be adding the new language as soon as possible.

**Comment by markwooff** [comment]
Language changes are now visible on the GCcollab Registration page: https://gccollab.ca/register

**Comment by patcon** [comment]
Thanks all!

@derekalton, can i haz invite pls? :) patrick.c.connolly@gmai.com
