### ISSUE TITLE
Move plugins that overlap with GCConnex to Composer

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gccollab#115]
Related to https://github.com/gctools-outilsgc/gcconnex/issues/426
During the hackathon we found the following plug-ins that appeared to be the same:
- [x] b_extended_profile
- [x] gc_api
- [x] gc_group_deletion
- [x] GC_profileStrength
- [x] GoC_dev_banner
- [x] ideas
- [x] missions
- [x] missions_organization
- [x] missions_profile_extend
- [x] toggle_language
- [x] unvalidated_user_cleanup
- [x] wet4
- [x] achievement_badges
- [x] cp_notifications
- [x] custom_error_page
- [x] c_email_extensions
- [x] c_members_byDepartment
- [x] c_module_dump
- [x] gcforums
- [x] gcProfilePicturesBadges
- [x] gcRegistration 
- [x] widget_manager_accessibility

When we compared the following were actually different:
- wet4
- b_extendend_profile
- c_email_extensions (my just be behind)
- c_members_byDepartment
- c_module_dump (maybe just behind)
- cp_notifications
- gc_api
- GC_profileStrength
- gcRegistration
- missions
- missions_profile_extend

**Comment by markwooff** [comment]
@nschonni yes, a good majority of these plugins are shared between GCconnex and GCcollab. The ones that differ are either behind on updates or have been customized for GCcollab. Most plugins would be great candidates for using Composer.

**Comment by markwooff** [comment]
The following modules differ between GCcollab and GCconnex, the ones that are checked off have been added in a [new branch](https://github.com/gctools-outilsgc/gcconnex/tree/merge_collab_into_connex) for merging:

- [x] `b_extended_profile` overrided by `b_extended_profile_collab`
- [x] `gcRegistration` overrided by `gcRegistration_collab`
- [x] `gc_splash_page` overrided by `gc_splash_page_collab`
- [x] `gccollab_theme`
- [x] `GC_profileStrength` overrided by `GC_profileStrength_collab`
- [x] `gc_onboard` overrided by `gc_onboard_collab`
