### ISSUE TITLE
User unable to change email from @cbsa.gc.ca to unitedwayottawa.ca

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#118]
Neither the user or an admin can change a user's email address from cbsa.gc.ca to unitedwayottawa.ca.

An error pops up saying "Not a government email address".

This is a functionality that GCcollab needs now that it is open by invitation.

**Comment by markwooff** [comment]
@JOutram77 The only issue with this is that each invitation that is sent out is for one specific email address, not the entire domain. Would either have to add that domain (**unitedwayottawa.ca**) to the Domain Manager or I can manually change their email address for them in the database.

**Comment by sdkibb** [comment]
I changed it in the DB for this user but Jeff was saying he still can't change the email after he adds it to the domain manager.

**Comment by markwooff** [comment]
Really? I just tried changing my email address to a unitedwayottawa.ca domain:

![image](https://cloud.githubusercontent.com/assets/5591488/25188034/b5d826b4-24f2-11e7-9cfd-a350da103a9b.png)

**Comment by sdkibb** [comment]
#hacker :p

**Comment by JOutram77** [comment]
I just had success. As an admin I was able to change the user's email through 'Edit Profile'. It didn't work through the admin settings. The email extension (eg. @unitedwayottawa.ca) is required to be in the domain manager. 

Perhaps we can make it so that users can change their email addresses to extensions that don't and won't exist in the domain manager.

**Comment by markwooff** [comment]
We could enable all email changes, but then a user would be able to sign up with an approved email & then change it to any email they'd like. This won't really matter once we open the platform to all.
