### ISSUE TITLE
Fatal Error Exception on Successful comment post

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#123]
This was happening in GCconnex so please speak with @Phanoix and bring over the fix (if available) from GCconnex.

 I posted a comment and received the Fatal Error screen of death (slightly redundant there). Upon going back to the page I could see that my comment was successfully posted. 

 This should be given high priority.

**Comment by markwooff** [comment]
Was discussing this issue with Derek today, he was able to provide a screenshot as well:

![image](https://cloud.githubusercontent.com/assets/5591488/25685277/6648b3b4-3034-11e7-90f9-135bb079cdc2.png)

**Comment by sdkibb** [comment]
Yeah, known issue with GCc team.

**Comment by ToferC** [comment]
Hi all - this is happening with GCconnex, but I think it's a different issue related to server load.  Regardless, the devs on both teams need to keep in touch.  We need to prioritize fixing this on GCcollab ASAP.  Thanks all.  @sdkibb @markwooff @Phanoix

**Comment by Phanoix** [comment]
I'll take a look at the collab logs, maybe they'll have more clues than the connex ones if these are in any way related.

**Comment by Phanoix** [comment]
That particular one is because it was trying to send a notification email that didn't have a subject.

**Comment by markwooff** [comment]
It seems to be stemming from the `cp_notifications` plugin, an exception is being thrown when there is no subject used for a notification email:

Exception #1493835904: exception 'NotificationException' with message 'NotificationException:MissingParameter' in /var/www/html/gccollab/mod/phpmailer/start.php:172
Stack trace:
#0 /var/www/html/gccollab/mod/cp_notifications/start.php(807)

Have you seen this on Connex before? Wonder if we should be setting a standard 'default subject' if there is none.

**Comment by sdkibb** [comment]
We should explore with a mindset that they are related given the similar error and successful posting  result. Could be server load is not the issue. Collab is way underutilized. I'll test more tonight on dev.

**Comment by Phanoix** [comment]
We probably get are some of those on connex.

**Comment by markwooff** [comment]
Just looking at the two repos & it appears the `cp_notifications` module on Collab is out of date already. Many changes done to this module on Connex. Mainly from https://github.com/gctools-outilsgc/gcconnex/commit/9c5f6efaa8972386b3c80933489e6be082120120

**Comment by Phanoix** [comment]
Yeah, looks like the connex version shouldn't have this particular problem.

**Comment by markwooff** [comment]
@Phanoix I know we did one recently, but do you think we could do another code pull from connex to collab? Should cover a lot of those accessibility changes done recently too.

**Comment by Phanoix** [comment]
Should probably merge the fix for this issue quickly first, and then get the rest up to the end of this sprint.

**Comment by markwooff** [comment]
I've merged the relevant notification changes from the PR https://github.com/gctools-outilsgc/gccollab/pull/124 and placed into dev. @sdkibb you will be getting lots of emails from my testing of notifications to verify the `NotificationException` doesn't appear again.

Will merge into prod after testing is completed.

**Comment by markwooff** [comment]
Fix for this exception has been pushed into prod from the latest PR https://github.com/gctools-outilsgc/gccollab/pull/125.
