### ISSUE TITLE
URL appearing in random contents (after adding hyperlink in CKEditor)

### ISSUE THREAD

**Issue by pandurx** [gctools-outilsgc/gccollab#13]
creates issue for the search (unexpected behaviour that causes the GSA to recursively index the same page)

**Comment by pandurx** [comment]
This has been resolved in Sprint 3 - random link still appears in content but users would need to go in and modify the hyperlink (this does not affect GSA anymore)

**Comment by Troy-Lawson** [comment]
thanks

**Comment by pandurx** [comment]
- there has been sightings in the source code that the url contains special characters (this is somehow only applied to older documents)
- when a user copy and pastes content from Outlook, the security software appends block:: to the URL which breaks source code

**Comment by pandurx** [comment]
see pull request [Zube #675](https://zube.io/tbs-sct/gctools/c/675)
