### ISSUE TITLE
The 'Latest Polls' widget is not displaying correctly in Groups

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#131]
A GCcollab user identified this bug. He says, 

"I added the 'Latest Poll' widget to my groups main page but it doesn't display the 2 polls that I had created. It says "There are no polls for {my group name} yet"  The only way to display the polls are to use the 'Latest Community Poll' widget, but that shows polls from other groups which I don't want. What is the best way to show my group community the polls I've created?"

This can be found at: https://gccollab.ca/discussion/view/44601/polls-in-group-pages

**Comment by markwooff** [comment]
Issue has been fixed with latest commit 5eeacbfccbea86e8795ff4db66a560a23b1cd85d. I imagine this issue wasn't noticed for a while since the polls aren't used very often.

**Comment by markwooff** [comment]
@Phanoix this is most likely an issue on GCconnex as well, even though the polls aren't used very often it might be a good idea to pull in these changes.
