### ISSUE TITLE
Add new opportunity types to Opportunity Platform

### ISSUE THREAD

**Issue by markwooff** [gctools-outilsgc/gccollab#141]
1) Casual Work (?) <-- Hover Box or more details : [Casual workers are hired for specified periods that may not exceed 90 working days in one calendar year, in a department or in an agency to which the Public Service Commission (PSC) has exclusive authority to make appointments. The period of casual employment may be for one or more than one term, but is not to exceed 90 working days in a department or agency in a calendar year.]

- Seeking
- Offering

French:

Emploi occasionnel <-- Hover Box or more details : [Les employés occasionnels sont des travailleurs embauchés pour une période déterminée ne dépassant pas 90 jours ouvrables par année civile dans un ministère ou organisme pour lequel la Commission de la fonction publique (CFP) a le pouvoir exclusif de faire des nominations. La période d'emploi temporaire peut être pour une ou plusieurs périodes déterminées, mais elle ne doit pas dépasser 90 jours ouvrables dans un ministère ou organisme par année civile.]

- Recherche
- Offre

2) Student Integration (?) <-- Hover Box or more details : [Any graduate of a post-secondary program who worked as a student employee for the Federal Public Service, via FSEWP, COOP, or RAP, may be considered for integration.]

- Seeking
- Offering

French:

Intégration des étudiants (?) <-- Hover Box or more details : [Tout diplômé d'un programme postsecondaire qui a travaillé comme étudiant salarié à la fonction publique fédérale, via PFETE, COOP ou PAR, peut être considéré pour intégration.]

- Recherche
- Offre

==========

These would need to be added to the “Opt In” section of GCcollab profiles, as well as to the types of opportunities in the Opportunities Platform that can be created, filtered, searched for, and for which analytics can be generated.

**Comment by markwooff** [comment]
Should hoverbox definitions be placed in modal for new users? (screenshot below)

![image](https://user-images.githubusercontent.com/5591488/26839473-19e7d9d6-4ab1-11e7-8f02-57cbee21423a.png)

**Comment by ToferC** [comment]
Yes, but should include offering / seeking for all opportunity types.

**Comment by markwooff** [comment]
@ToferC see updated user profiles at https://dev.gccollab.ca/profile/Mark.Wooff that include Offering / Seeking for Casual and Student opportunities.

![image](https://user-images.githubusercontent.com/5591488/27236520-574b4328-5293-11e7-93cb-126bf5359168.png)

![image](https://user-images.githubusercontent.com/5591488/27236554-718fa364-5293-11e7-89ea-3b6fd63b5e19.png)

![image](https://user-images.githubusercontent.com/5591488/27236480-32a728d4-5293-11e7-834a-c78283014fac.png)

**Comment by ToferC** [comment]
Can't see the fields. Private?

**Comment by markwooff** [comment]
Casuals & students have been added to the GCcollab Opportunities Platform. Closing issue.
