### ISSUE TITLE
Can't post in French on mobile app

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gccollab#142]
Tried posting this to the wire:

Belle journée pour la foire de l'innovation ! #ob2020 #noussommesinnovateur #gccollab #outilsgc

Shows up blank

**Comment by markwooff** [comment]
Wire message is now being utf8 encoded to allow for French characters.

**Comment by PhilAndrecheck** [comment]
Just tested, works! Merci!
