### ISSUE TITLE
Title on colleagues (friends) page

### ISSUE THREAD

**Issue by lchski** [gctools-outilsgc/gccollab#143]
The title of the page at `/friends/{username}` reads as “{Name}’s my colleagues”/«{Nom}’s mes collègues». The French translation is rough even without the extra apostrophe, though I’m not qualified to properly translate that. I’m not sure why the “my” is slipping in there, [the translation files for the string](https://github.com/gctools-outilsgc/gccollab/blob/gccollab/languages/en.php#L211) don’t seem to have it, but I may be looking in the wrong place (still figuring elgg out).

This behaviour is especially odd if you load the page of another user (substituting their username in the URL)—it still reads as “{Name}’s my colleagues”.

Screenshot ([source URL](https://gccollab.ca/friends/Lucas.Cherkewski)):

![screen shot 2017-06-01 at 12 51 38 pm](https://cloud.githubusercontent.com/assets/343884/26690892/12a7db1c-46c9-11e7-924e-21f9ca61013a.png)

Happy to submit a PR, just not sure why this is behaving as it is.

**Comment by markwooff** [comment]
Hi @lchski, thanks for bringing this to our attention. The language file was changed recently to show corrected strings however it looks like the Elgg cache was still storing the old strings. This should be updated now.

In case you were curious, the translation files you had linked are the core files that come with Elgg. We usually override these strings in separate modules, in this case the WET4 language files will override as seen here: https://github.com/gctools-outilsgc/gccollab/blob/gccollab/mod/wet4/languages/en.php

**Comment by lchski** [comment]
Awesome, it now shows correctly. Thanks @markwooff! Notes like that make it easier to contribute in the future :+1:
