### ISSUE TITLE
Add the 'Filter Items' function to each tab of the 'groups' section

### ISSUE THREAD

**Issue by markwooff** [gctools-outilsgc/gccollab#147]
The option currently only exists for the 'My Groups' tab:

![image](https://cloud.githubusercontent.com/assets/5591488/26787847/5b9f7f2e-49d9-11e7-9a9d-18e0dd14b488.png)

**Comment by ToferC** [comment]
Might not want to do this. Filter depends on data tables and having 7000
plus groups in a table might hurt performance. Pls. Assess. Tks!

**Comment by markwooff** [comment]
Performance wouldn't take too much of a hit with the ~200 groups currently on GCcollab, but as this grows the feature would get more & more sluggish. Perhaps best to leave out.

**Comment by markwooff** [comment]
Reverted changes with 5c67365bd2096ce70c1496b65979bd71bd3fc59a. Closing issue.
