### ISSUE TITLE
Enable validated users to change their email to whatever they want

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gccollab#148]
If a user has been validated (either via white list or by invitation) to be a user on GCcollab, he or she should be able to change their email to whatever they want, with a simple validation from them before the change is approved to ensure it is a real email to which they have access.

After discussion, the project team would like this functionality to be created for GCcollab in the first available sprint.

**Comment by markwooff** [comment]
@PhilAndrecheck feel free to test new function on the dev site at https://dev.gccollab.ca/profile/

**Comment by JOutram77** [comment]
Intuitively, there are two ways for a user to potentially change their email address:
1) My Profile 
2) Account Settings

Unfortunately, option 2 does not currently save a new email address even one that should be accepted. The error given simply says "Not a Government email address". Can this be fixed?

**Comment by markwooff** [comment]
Hey @JOutram77, to be honest I didn't even know you could also change your email address from the **Account Settings** area. I've added the same functionality to this page as exists on the **My Profile** edit page.

**Comment by JOutram77** [comment]
AT Phil's request, can this issue be revisited? The issues remain on Prod. Users are unable to change their email addresses from Account Settings.

**Comment by markwooff** [comment]
@JOutram77 just tested it & received the confirmation email just fine... could you please test again on your end? Thanks.

**Comment by markwooff** [comment]
@JOutram77 @PhilAndrecheck are there still issues with this? Not sure if you've had a chance to test on your end or not.

**Comment by JOutram77** [comment]
I did testing today. It worked well. The new email address be saved instantly, however are we not going to require a validation email be sent to the new email address?

**Comment by markwooff** [comment]
@JOutram77 email validation is required if the email address is not on the list of approved domains. For example, if a user tries to changes their email address to `joe.schmoe@gmail.com` then they will be required to validate this via an email sent to that address.
