### ISSUE TITLE
Add invite colleague button under main nav-bar

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gccollab#152]
User Story: As a regular user I need a simple way to invite colleagues to join GCcollab.

Suggest a new button: "Invite" right beside the colleagues button that allows users to add a list of email addresses, either semi-colon or line separated. 

Let's make it easy and fast for users to invite colleagues from outside our white-listed organisations.

**Comment by markwooff** [comment]
Something along the lines of the following screenshot?

![image](https://user-images.githubusercontent.com/5591488/28038609-824ad7e8-658d-11e7-9242-ec7ff2131a17.png)

**Comment by ToferC** [comment]
Maybe a button to give some contrast and "Invite to GCcollab" for context?
Open to suggestions. Just a bit worried folks won't see it.

**Comment by markwooff** [comment]
Definitely stands out a bit more with the button styling:

![image](https://user-images.githubusercontent.com/5591488/28042438-40af51a2-659b-11e7-9bcc-16b3f13f4c84.png)

**Comment by ToferC** [comment]
+1

**Comment by markwooff** [comment]
Made it easier for users to input multiple email addresses using the 'tag' method:

![image](https://user-images.githubusercontent.com/5591488/28073633-5aec44ce-6624-11e7-96be-04542450e9b3.png)

**Comment by JOutram77** [comment]
Just a suggestion but if I was going to invite a number of colleagues on to GCcollab, I won't type them out, but instead would open an email, type names in the TO: bar and cut and paste it into the GCcollab invite field. Is this something that could be supported in addition to what you've added here to day Mark? 

The text would look like:

Wooff, Mark <Mark.Wooff@tbs-sct.gc.ca>; Outram, Jeffrey <Jeffrey.Outram@tbs-sct.gc.ca>; Alton, Derek <Derek.Alton@tbs-sct.gc.ca>

Perhaps should be another issue on here on GitHub.

**Comment by markwooff** [comment]
Hi @JOutram77 ,

The current functionality actually supports this copy & paste technique, however only with email addresses. If you type in "Mark.Wooff@tbs-sct.gc.ca; Jeffrey.Outram@tbs-sct.gc.ca; Derek.Alton@tbs-sct.gc.ca" and hit enter, it'll parse the text as three separate email addresses.

![image](https://user-images.githubusercontent.com/5591488/28079519-bd75ee6c-6636-11e7-805b-f637fd724eb1.png)

**Comment by ToferC** [comment]
Could we extract email addresses from raw text with other info?

I agree with Jeff - entering multiple email addresses is a huge pain.

**Comment by markwooff** [comment]
@ToferC @JOutram77 actually just made a quick change on this.. if you enter the text that Jeff originally posted, the form will now parse out the email addresses and ignore the text that is not formatted as an email address:

![image](https://user-images.githubusercontent.com/5591488/28080213-26117804-6639-11e7-8dfc-25806a4125f3.png)

**Comment by markwooff** [comment]
This is now live on production, closing issue.

**Comment by ToferC** [comment]
@wooff - is the one email per line still accurate? What about "Paste or
enter your email addresses below."

**Comment by markwooff** [comment]
Sounds good to me. Is this accurate for French: "Coller ou entrer votre adresse courriel ci-dessous."

**Comment by ToferC** [comment]
vos adresses = good!

**Comment by ToferC** [comment]
Collez ou entrez vos adresses courriel ci-dessous

**Comment by ToferC** [comment]
Button is only visible from desktop view. It should show up on-screen. Can you also create a new issue for: port new email invite functiinality to gcconnex and add same functionality to all email invite fields (groups).

@lawson-troy @phanoix fyi.

**Comment by markwooff** [comment]
PR has been created with https://github.com/gctools-outilsgc/gcconnex/pull/1243 that includes the new functionality for GCconnex. Porting over to other email fields will need to be done on both GCcollab and GCconnex.

**Comment by markwooff** [comment]
Will need to do some work on the mobile view for the new button as it crowds up the top nav.

**Comment by markwooff** [comment]
Proposing we combine the branding with the top search/menu bar to save real estate and allow for more visible options on mobile. Look & feel would go from:

![image](https://user-images.githubusercontent.com/5591488/28124884-e92eed30-66f2-11e7-9668-ccc44566b410.png)

To this:

![image](https://user-images.githubusercontent.com/5591488/28124967-2d285d64-66f3-11e7-954d-394e426da420.png)

**Comment by ToferC** [comment]
Beautiful.
