### ISSUE TITLE
Government of Quebec public servants can't register

### ISSUE THREAD

**Issue by gabrielcossette** [gctools-outilsgc/gccollab#16]
Hi,

Someone from this quebec provincial deparment can't register. It says "Invalid Email":

http://cspq.gouv.qc.ca
XXXXX@cspq.gouv.qc.ca

Thanks!

**Comment by Phanoix** [comment]
added the email extension

**Comment by gabrielcossette** [comment]
The cspq one now works but just found another one which doesn't: @msp.gouv.qc.ca

Why not add the whole @*.gouv.qc.ca extension? There are many sub-domains...

**Comment by spvtnik** [comment]
And some with .qc.ca or .ca only should not to be forget like http://www.revenuquebec.ca or http://www.csst.qc.ca.

**Comment by gabrielcossette** [comment]
Any news? Thanks!

**Comment by Phanoix** [comment]
@JOutram77  @sdkibb

**Comment by sdkibb** [comment]
On it.

**Comment by markwooff** [comment]
@sdkibb just for curiosity's sake, would the fix for this be adding these additional domains to the **Domain Manager** plugin?

**Comment by sdkibb** [comment]
Yes, it's under settings in the plugin made by Christine. I need to confirm that all qc ca are provincial employees.

**Comment by sdkibb** [comment]
@phanoix Is there wildcard functionality? If not we will need to put it in. Thinking of *gc.ca or just gc.ca but it looks like Jeff put in every dept individually so wondering if there was a reason for that.

**Comment by Phanoix** [comment]
I don't think that mod currently has wildcard functionality.

**Comment by gabrielcossette** [comment]
A *.gouv.qc.ca wildcard would cover the majority of QC provincial employees. Then additional static entries for specific .qc.ca or .ca that @spvtnik was referring to.

Don't add *.qc.ca as it covers more than government. A citizen can't order new .qc.ca but those who already have one can keep it.

**Comment by markwooff** [comment]
Wildcard functionality was added with the latest commit 3dd4a3a1abaa608c60a820105eac23efa455cdab.

You can now enter email extensions in the format of `*.xyz.com` where anything replacing the asterisk will be accepted for registration. This would include emails such as `test@one.xyz.com` or `another@one.two.xyz.com`.

**Comment by markwooff** [comment]
@sdkibb added label to this feature as it will most likely be used in GCconnex as well

**Comment by JOutram77** [comment]
FYI  *.gouv.qc.ca  was added to the domain manager.

**Comment by ghost** [comment]
Does it mean the change is supposed to be live? I just tried "@msp.gouv.qc.ca" and it doesn't work.

**Comment by markwooff** [comment]
@gabrielcossette-ca what error message are you receiving? I just pushed the latest changes to the live site, please try registering again.

**Comment by ghost** [comment]
It works now, thanks! For any new email extension, we just open a new Github issue?

**Comment by JOutram77** [comment]
Gab, please feel free to create issues for this or other GCcollab issues. We appreciate the support.

**Comment by ghost** [comment]
Super. You can close this issue now (or keep it open if you want to migrate the functionality to GCconnex code base).
