### ISSUE TITLE
Add Hello World Wire Post

### ISSUE THREAD

**Issue by derekalton** [gctools-outilsgc/gccollab#166]
Have a function added so that when a new user creates their profile, they are prompted to write a wire post introducing themselves to the GCcollab community.

E.g. Say hi and something that you are interested in or a question you have.

**Comment by markwooff** [comment]
We could either create a new module for this or add it as part of the onboarding. The latter makes the most sense.

**Comment by markwooff** [comment]
@derekalton this feature has been added to the dev site, feel free to test it out using this link: https://dev.gccollab.ca/newsfeed?welcome=true

New users will see the onboarding module by default, but it can be seen again by using the above link or going to the Tutorials section of the site. **Step 5** is what you'll be interested in:

![image](https://user-images.githubusercontent.com/5591488/28891332-1a57c048-7798-11e7-87b9-56d6d7a26617.png)

**Comment by markwooff** [comment]
We'll just need to figure out the text displayed to the user. Right now the intro paragraph is **Feel free to test out The Wire below! Say hi and something that you are interested in or a question you have.** After posting, the user will see **Great! Thanks for sharing.** Thoughts?

**Comment by markwooff** [comment]
@LemieuxGen thinking that we could have some better language here for the onboarding text as the current text is shown in the screenshot above.. thoughts?

@sdkibb the language text can be updated in the `mod/gc_onboard_collab/languages/**.php` files, just look for the keys `onboard:wire4` and `onboard:wire_success`.

**Comment by sdkibb** [comment]
Ok, I'll change as needed.

**Comment by LemieuxGen** [comment]
@sdkibb ; what about the following text: 
Don’t be shy, try it out! Post a Wire message about your latest updates, let others know about interesting events and projects coming up, or simply ask that question you’ve been pondering… 
 _After posting, the user will see_ 
Great! Can’t wait to see what you’ll be sharing next! 


FRENCH
Ne soyez pas timide, essayez-le! Publiez un message sur le Fil au sujet de vos dernières nouvelles, faites pars des événements et des projets intéressants à venir, ou posez simplement cette question sur laquelle vous songez...
_After posting, the user will see_ 
Génial! Nous avons hâte de voir ce que vous partagerez la prochaine fois!

**Comment by LemieuxGen** [comment]
@JOutram77 tagging you on this. Are you ok with the text?

**Comment by JOutram77** [comment]
@LemieuxGen in the English, I'd remove the word 'on' after 'pondering'. Other than that, sounds great.

**Comment by LemieuxGen** [comment]
Great, thanks @JOutram77. @sdkibb good to go, the text has been updated in the comment above. Thanks!

**Comment by markwooff** [comment]
Thanks @LemieuxGen - I've updated the language with the text you've provided here. Closing issue.
