### ISSUE TITLE
Reorder Search Responses

### ISSUE THREAD

**Issue by derekalton** [gctools-outilsgc/gccollab#167]
This is a request to re-order the search responses in a more intuitive order based on UX testing.  The following order is proposed:

users, groups, discussions, files, blogs, wire posts, comments, bookmarks.

**Comment by sdkibb** [comment]
Agreed that this should be implemented.

**Comment by ToferC** [comment]
Approved.

**Comment by markwooff** [comment]
New order for search results is now live on GCcollab.ca
