### ISSUE TITLE
Invite to group by email not working

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gccollab#168]
Group owners get "The action file for groups/Invite not found" error. 

This should be a priority fix pls.

Also, on mobile, selecting settings as group admin has the drop-down options overlapping with group content hyperlinks.

**Comment by markwooff** [comment]
This has now been fixed by re-ordering the plugins in the Elgg backend. Thanks!

**Comment by ToferC** [comment]
Thanks so much, @wooff

**Comment by markwooff** [comment]
@ToferC I can fix the mobile issue as well but not sure where exactly you mean, this is how I see the Settings dropdown on mobile:

![image](https://user-images.githubusercontent.com/5591488/28502922-8c755f6c-6fca-11e7-88d3-3f5cec08383e.png)

**Comment by ToferC** [comment]
On Chrome Samsung Galaxy s7 edge. 

![screenshot_20170723-175308](https://user-images.githubusercontent.com/6226762/28503210-22e0971e-6fd0-11e7-9ae9-2a55455a9b49.png)

**Comment by markwooff** [comment]
Was able to reproduce, some odd CSS was being tacked onto the entire Group header if a cover photo exists. This has now been fixed.

**Comment by ToferC** [comment]
Thanks, Mark!
