### ISSUE TITLE
Remove opportunity types from "Opt In" drop-down menu in Find Members, Advanced Find 

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gccollab#169]
In Opportunities Platform -> Find Members ->Advanced Find, the Opt In field should only include a drop down list of Mentoring, Casual Work and Student Integration. Currently the drop down menu shows all the mechanism supported on the GCconnex platform.

**Comment by markwooff** [comment]
Hi @Eldoraaoun, this has now been fixed. Thanks for bringing this to our attention.
