### ISSUE TITLE
Unable to add file folder on upload

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gccollab#17]
When uploading a file, choosing to add a new folder generates a JS error.

{"current_url":"https:\/\/gccollab.ca\/file_tools\/folder\/new\/0?folder_guid=","forward_url":"https:\/\/gccollab.ca\/file\/all","output":"","status":0,"system_messages":{"error":[],"success":[]}}

**Comment by markwooff** [comment]
Fixed action for "New file folder" button can be seen at http://gccollabdev.canadaeast.cloudapp.azure.com/file/all

**Comment by sdkibb** [comment]
Seems to work fine now. Closing this.
