### ISSUE TITLE
Problem with pages

### ISSUE THREAD

**Issue by ThomKearney** [gctools-outilsgc/gccollab#172]
Can someone tell me what is happening here? 
This is a page we want to collaborate with others on…..

https://gccollab.ca/pages/view/49803/endeveloping-a-guide-to-public-engagementfru00c9laborer-un-guide-de-la-participation-du-public

![capture](https://user-images.githubusercontent.com/3384295/28923464-2cc8c59e-782c-11e7-9392-4ea7cf31bd9a.PNG)

**Comment by sdkibb** [comment]
Sorry Thom, we'll have it fixed. Some accessibility changes made some things waky.

**Comment by ThomKearney** [comment]
Thanks!
