### ISSUE TITLE
Add a new 'Type of Opportunity' to the Opportunities Platform, and augment the following fields for the new opportunity type

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#178]
It's our understanding that changing the fields of an opportunity type can mess with the analytics, hence why some of the ALL-CAP comments below provide conditions.

- Step 1: Poster information
  - Your name: 
  - Your organization, agency or department: 
  - Your email:
  - Phone number:

- Step 2: Opportunity Details
  - Bilingual opportunity title:
  - Opportunity role:
  - Type of opportunity: ADD COLLABORATION
  - Program area:
  - Group/Classification: NOT DISPLAYED – IF NOT POSSIBLE TO NOT DISPLAY, GREYED IT OUT
  - Number of opportunities: ADD UNLIMITED AS AN OPTION
  - Ideal start date: REMOVE REQUIRED IF IT DOES NOT IMPACT ANY BACK-END OR ANALYTICS
  - Ideal completion date:
  - Application deadline:
  - Bilingual description of opportunity:

**Comment by markwooff** [comment]
@JOutram77 just to confirm, is the new type of opportunity called "Collaboration" as to look like the following screenshot?

![image](https://user-images.githubusercontent.com/5591488/30213037-51cbe71c-9475-11e7-8ece-3e202c9f44bc.png)

**Comment by markwooff** [comment]
@JOutram77 This is now up on dev, however the required Start Date will have to remain for analytics purposes. Feel free to test on [dev](https://dev.gccollab.ca/missions/main). See screenshot:

![image](https://user-images.githubusercontent.com/5591488/30861551-0eab0918-a299-11e7-922e-9d31e04ad119.png)
