### ISSUE TITLE
Whitelisting of Export Development Canada email domain

### ISSUE THREAD

**Issue by JPDub3** [gctools-outilsgc/gccollab#180]
Emails from Export Development Canada aren't white-listed despite having this organization listed under a Federal Government Organization. 

Requesting to have "edc.ca" domain to be white-listed for registration.

**Comment by JOutram77** [comment]
@JPDub3 thanks for opening this issue. I just double checked and edc.ca is whitelisted for registration of GCcollab. Are you having issues registering an account?

**Comment by JPDub3** [comment]
Yes. I had trouble earlier. I've just tried again and it worked!

**Comment by JOutram77** [comment]
Great. Glad to learn that you were able to register. I look forward to connecting on GCcollab.
