### ISSUE TITLE
Registration page: multiple issues

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#181]
1. Who can register text does not include retired public servants
2. Mandatory Institution dropdown menu has usability issues. Why should retired public servants have to identify their organization according to a current list? How is that relevant, and what if the organization no longer exists. Does "other" occupation allow to input a new organization or dropdown only? (I wasn't able to verify
3. Display name instructions in French need to be updated, to reflect workplace/school 
4. Typo in last para, "copy past**e**
5. Suggest including a timeframe for receipt of validation email. If you do not receive the email within xx hours.... please contact... 
6. Recommend review of the French text on the registration page. 
6. I could not verify the process because of reCAPTCHA errors. "Cannot contact reCAPTCHA. Check your connection and try again."

**Comment by markwooff** [comment]
1. What text should be added & where?
2. **Retired** users can enter any custom text they would like in the "Organization" field, but as a user types they are provided with suggestions provided based off the GoC federal departments. **Other** users are provided with the same free text field with suggested options.
3. What text should be added & where?
4. Typo has been fixed.
5. What text should be added & where?
6. Is there any French text that should be changed?
7. Did this happen on IE & on your TBS machine?
