### ISSUE TITLE
Adding hot keys to docs

### ISSUE THREAD

**Issue by derekalton** [gctools-outilsgc/gccollab#182]
Can we add hot keys features to docs function.  Specifically I want the ability to embed links in texts (ctrl. k)

**Comment by sdkibb** [comment]
Not at my desk but are you able to bold, underline etc. with hotkeys?

**Comment by derekalton** [comment]
Good point we did a test and you are right.  The issue isn't the hot key, the issue is the ability to embed links in the document (and the corresponding hot key)

**Comment by markwooff** [comment]
The ability to embed links into text (a la Google Docs) isn't built into Etherpad by default unfortunately. There is a plugin (https://github.com/inicio/ep_embedded_hyperlinks) that attempts to add this functionality but after testing it out it appears to have many bugs.

I've created an issue on their repo to see if the plugin will continue to be developed.

**Comment by ToferC** [comment]
Thanks @wooff. Let's close the issue.
