### ISSUE TITLE
Having the ability to select a doc in the widget for doc

### ISSUE THREAD

**Issue by derekalton** [gctools-outilsgc/gccollab#183]
I have created a group and added a widget for docs.  It would be great (and intuitive) to have a button in the widget itself allowing me to create new docs, instead of having to go to the group menu and find it.

**Comment by markwooff** [comment]
The Docs widget will now have a "Create a new Doc" button at the top-right for easy access, along with an "All Docs" button at the bottom. See screenshot below:

![image](https://user-images.githubusercontent.com/5591488/29853050-9cdadc98-8d0b-11e7-806d-31acbf181786.png)
