### ISSUE TITLE
Ajax success callbacks displayed after login

### ISSUE THREAD

**Issue by markwooff** [gctools-outilsgc/gccollab#19]
After logging in from the [login page](https://gccollab.ca/login), the browser was redirected to the following URL https://gccollab.ca/analytics/ajax_success instead of the News Feed. The JavaScript functions below were being displayed directly in the browser (invalid headers?):

`ga('send', 'event', {"eventCategory":"user","eventAction":"login:before","eventLabel":"Mark Wooff"});ga('send', 'event', {"eventCategory":"user","eventAction":"login","eventLabel":"Mark Wooff"});ga('send', 'event', {"eventCategory":"user","eventAction":"login:after","eventLabel":"Mark Wooff"});`

**Comment by sdkibb** [comment]
More info on this: I think it is because this JS is written and flushed out of the http buffer before the redirect happens. We have to check the GA reports and decide if we even need this type of action in our reports. I doubt we use it. Unless someone tells me we need it I'm going to remove the GA event call altogether.

**Comment by sdkibb** [comment]
Done but requires more testing. If anyone sees this error again LMK otherwise I will close this in the next little while.

Modified the /mod/analytics/pages/ajax_success.php and commented out the echo.

**Comment by nschonni** [comment]
Just got this too
```
ga('send', 'pageview', '/action/login/succes');ga('send', 'event', {"eventCategory":"user","eventAction":"login:before","eventLabel":"Nick Schonning"});ga('send', 'event', {"eventCategory":"user","eventAction":"login","eventLabel":"Nick Schonning"});ga('send', 'event', {"eventCategory":"user","eventAction":"login:after","eventLabel":"Nick Schonning"});
```

**Comment by piet0024** [comment]
https://github.com/gctools-outilsgc/gccollab/issues/225

**Comment by markwooff** [comment]
Also just encountered being redirected to the URL https://gccollab.ca/ajax/view/ajax/newsfeed_check?userid=5374&limit=1

![image](https://user-images.githubusercontent.com/5591488/34022024-dc5e35b0-e10a-11e7-8466-00e7a22bc5e4.png)

**Comment by markwooff** [comment]
Issue should now be fixed, duplicate of https://github.com/gctools-outilsgc/gccollab/issues/225. I think the cause of the issue was the favicon flow:

1. When a browser first loads the site, it sends the first HTTP request to get favicon.ico not the actual page the user requested.
2. An HTTP session is created and the first requested object is stored with the session.
3. Elgg sends the user a redirect to the "Page not found" page instead of a 404 for a missing favicon or file.

When testing on mobile, the browser would request a mobile favicon (which didn't exist) and redirect them to https://gccollab.ca/mod/wet4_collab/graphics/favicon-mobile.png. I've placed a copy of our favicon there so the 404 doesn't appear.
