### ISSUE TITLE
Content created in French tab for new discussion topic not detected in french language.

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#190]
When a user types in content in the French tab of a new discussion topic, words are not being recognized in the appropriate language and so underlines it as an error: (spell-check).  This happens in the field for the title of the discussion topic:

![french tab spellcheck gccollab](https://user-images.githubusercontent.com/23527358/29686843-6ffa7c96-88e8-11e7-804b-467a33aaa988.PNG)

I tested this in GCConnex and the issue seems to be present there as well (but it doesn't happen in the tittle field):

![french tab spellcheck gcconnex](https://user-images.githubusercontent.com/23527358/29687079-32ec346a-88e9-11e7-91f6-41ad01367e6a.PNG)

GCconnex GitHub ticket: https://github.com/gctools-outilsgc/gcconnex/issues/1365

**Comment by nschonni** [comment]
I believe you're just talking about the browser built in spellchecking, rather than a feature/bug of Elgg itself. You'd need to manually switch languages/dictionaries yourself.

**Comment by markwooff** [comment]
Yes, this is due to the user's browser settings - nothing we can code into GCconnex or GCcollab to fix this. Closing issue.
