### ISSUE TITLE
Title of "Email address change request for GCcollab" not bilingual 

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#191]
Title is English only. Content is bilingual 
![gccollab - email address change request](https://user-images.githubusercontent.com/24227707/29717490-5c5085e2-897d-11e7-9826-0ea1e18d6d96.JPG)

**Comment by markwooff** [comment]
@joymosk do you propose we use both titles in a single line? For example:

**Email address change request for GCcollab | Demande de changement d'adresse de courriel pour GCcollab**

**Comment by ghost** [comment]
Yes. I believe that's how the others are set up. Thanks.

**Comment by markwooff** [comment]
Change has been made, thanks @joymosk !
