### ISSUE TITLE
"breadcrumb" of filters applied when searching Opportunities

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#193]
In the Opportunities page, there are filters and sort options in the same area, but the button only says Sort.  

Would be nice to see "breadcrumbs" showing what the filters and sort options were - as seen in GCConnex;

GCcollab:

![opportunity filter gccollab](https://user-images.githubusercontent.com/23527358/29835649-a78ed658-8cc0-11e7-986c-ffac08bdbfd5.PNG)

GCConnex:

![opportunity filter gcconnex](https://user-images.githubusercontent.com/23527358/29835742-e76b7e84-8cc0-11e7-831c-a8f0c216b77f.PNG)

**Comment by markwooff** [comment]
These changes to GCconnex will be pulled into GCcollab as part of this sprint.
