### ISSUE TITLE
Features display in group menu (under More) even when feature is not enabled by Group Owner/Operator

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#194]
![edit group content options](https://user-images.githubusercontent.com/24227707/29881527-d5b435e2-8d78-11e7-80ae-7d286a089d1d.JPG)
![group more menu](https://user-images.githubusercontent.com/24227707/29881528-d5d12198-8d78-11e7-84fd-fed846845f78.JPG)

**Comment by markwooff** [comment]
Issue has been fixed as part of the latest code push. Closing issue.
