### ISSUE TITLE
My colleagues widget for groups widget menu should not be available 

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#195]
My colleagues is a widget option for Group Owner and Operator. Widget does not work. Please remove.  Does not exist in GCconnex.

**Comment by markwooff** [comment]
Widget options will be the same as GCconnex after I pull the code into GCcollab. Should be done by the end of this sprint.

**Comment by markwooff** [comment]
"My Colleagues" should no longer be an option for Group widgets. Can you verify @joymosk ?

**Comment by ghost** [comment]
Correct @markwooff

**Comment by markwooff** [comment]
@joymosk did you re-open because the issue still exists? If so, where did you see it?
