### ISSUE TITLE
Widgets of patents and publications should be able to add more than one

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#197]
As a user, if I have publications or patents I wish to display on my profile, I should be able to have the ability to add more than one. Currently I can only add one title with a link.

**Comment by markwooff** [comment]
Where is the user trying to place these publications/patents? They can add as much text as they'd like in the **About Me** section, would be a good place for these.

**Comment by JOutram77** [comment]
I think these are fields that should be added to profiles, similar to what's available on other sites like LinkedIn, Orcid and ResearchGate. It would be useful to help draw the academic and scientific communities. 

Perhaps this should be discussed when we develop the direct new directory in the coming months.

**Comment by ToferC** [comment]
Gcconnex allows users to add multiple publications. This should be
replicated on Collab.

**Comment by markwooff** [comment]
This will be carried over as part of the code port. Along with the Notification Digest.
