### ISSUE TITLE
Error msg and code on DOC page

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gccollab#199]
Page loaded fine, however after locking computer, then unlocking after 20 mins, page (https://gccollab.ca/docs/view/118379/team-vision-mission-objectives) open to doc had error msg with a lot of code:

![collaberrold](https://user-images.githubusercontent.com/22220521/29979793-f1283d76-8f14-11e7-851d-46ca1a18ffb9.PNG)

**Comment by ToferC** [comment]
Also to address: signout & "You do not have permission to edit this doc"
after a few minutes of editing.

**Comment by markwooff** [comment]
Found this earlier today: https://elgg.org/plugins/810759/releases/0.8.0#elgg-object-1763853

Will be looking at the feedback from one of the test Docs as well: https://gccollab.ca/docs/view/112558/whats-in-a-test-that-which-we-call-possibility

**Comment by markwooff** [comment]
All this time was looking at the Etherpad service to fix the issue, turns out it was the Elgg plugin that was causing this. Just pushed a change to prod that should eliminate the "disconnected" and "do not have permission" error messages.

Will keep an eye on it this week and see if the issue remains.

**Comment by ToferC** [comment]
Awesome. Thanks, @markwooff!

**Comment by ToferC** [comment]
Hi @markwooff - there are still connection issues from the full page view. Could you look at this? We're almost there!

**Comment by markwooff** [comment]
@ToferC it may have just been a one-off as I was just making some changes to the server. Let me know if it happens again though!
