### ISSUE TITLE
Develop the section of the registration page for municipal public servants.

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#200]
Municipal public servants currently using GCcollab have access by invitation, so the current registration page allows them to simply provide the name of their municipality. 

Now that we have the permission to open access of GCcollab to Canadian municipal public servants, we need to build that portion of the registration page.

**Comment by markwooff** [comment]
@JOutram77 we can discuss what language changes and/or form changes will need to be made to incorporate the addition of the Municipal user type.
