### ISSUE TITLE
The Chat function is displaying English, when in the French language.

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#201]

**Comment by markwooff** [comment]
Turns out that an apostrophe in the French text was causing the JS to error out. Issue has been fixed, could you verify on your end when you're back? Screenshot below:

![image](https://user-images.githubusercontent.com/5591488/30812533-ff03f7f6-a1d8-11e7-9451-cbbf605f90bc.png)

**Comment by markwooff** [comment]
Was also able to fix the "View Profile" link for each chat user, now points to the right link:

![image](https://user-images.githubusercontent.com/5591488/30813684-14df10c6-a1dc-11e7-87ce-e0924c03872f.png)
