### ISSUE TITLE
Social Accounts in 'Edit Basic Profile' not saving

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#203]
As a user, on my profile page I click **Edit** and have the option to input my social media account details to add to my profile. When I hit Save, I do not get the 'Your profile was successfully saved' green pop-up and my details are not saved.

I'm not sure if this is a bug because I can correctly add social media accounts to my profile and get the green pop-up confirmation like this:

![image](https://user-images.githubusercontent.com/29754185/30176892-fb116f58-93d1-11e7-85e0-b76b6b7abf21.png)

However, in this user's profile (username Josh.Beveridge) I can follow the exact same steps, click Save, do not recieve the green pop-up confirmation and the information doesn't save.
Note: the user synced their LinkedIn account before trying to add any other social media accounts. I synced mine after and was still able to add social media details. 

Link to the user's profile where this is occurring: https://gccollab.ca/profile/Josh.Beveridge

**Comment by JoshBeveridge** [comment]
As another point of reference (and as the user who originally reported the bug) I should note that I've tried unchecking my Linkedin imports and those don't seem to save either. Is there a way to remove the Linkedin connection entirely via the GCcollab UI? I'll try removing it via Linkedin in the mean time.

**Edit**: Nope, removing the token via Linkedin didn't change anything.

**Comment by markwooff** [comment]
Hi @joshdrink - looks to be an issue with the way some of the links on your profile were being saved. This has now been resolved - thanks!

**Comment by JoshBeveridge** [comment]
Hey @markwooff! Just confirmed that it's all working as expected. Thanks for the quick fix!

**Comment by markwooff** [comment]
No problem @joshdrink - happy to help! Closing issue.
