### ISSUE TITLE
Duplicate Event calendar widgets - only one works

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#204]
When adding a widget, there are two widgets labeled 'Event calendar'.

The first one in the list is broken and displays nothing in the widget, and the second functions properly.

**Comment by markwooff** [comment]
Thanks for flagging this @klecuyer, this issue has been fixed. Only one "Event Calendar" widget will be available now:

![image](https://user-images.githubusercontent.com/5591488/30380674-37e9115c-9868-11e7-84f8-d418d7da08b9.png)
