### ISSUE TITLE
When registering a new user, proper fields are not saved and user defaulted to Academic

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#207]
When I was creating a new user through the admin panel, I entered her information (Federal Government, Defense Construction Canada) the new user was created but when I checked her profile, all fields were blank and her account defaulted to Academic.
![image](https://user-images.githubusercontent.com/29754185/30605231-50a3ed34-9d3b-11e7-999e-67bab4a22b75.png)

I was creating the user's account because she got a Fatal Error message when trying to register:
![image](https://user-images.githubusercontent.com/29754185/30605256-66ecef3c-9d3b-11e7-8cd3-f125c1ecdd24.png)

**Comment by markwooff** [comment]
When did the user try registering their account? There was an error with the database this morning so just wondering if this is related.

Also just tested creating a new user from the admin panel and was able to set their department without an issue. Are you using IE to create the user? Tested on Chrome, will test on IE now.

**Comment by klecuyer** [comment]
I was using Chrome.

The ticket came in at 11:51am today.

Thanks!

**Comment by markwooff** [comment]
@klecuyer As a test, could you try adding a new user with a different user type to see if the issue remains?

**Comment by klecuyer** [comment]
I just tried creating with my own Gmail as a federal government employee and it all registered OK.. @markwooff

**Comment by markwooff** [comment]
The fatal error message should be fixed with the latest code push made over the weekend. Sounds like the user registration is working on your end so I'm going to close this issue. Can re-open if you ever run into that issue again.
