### ISSUE TITLE
Sub-group owner unable to accept join request

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#208]
When trying to accept a Join Request for a sub-group ( https://gccollab.ca/groups/profile/124519/enfgp-standard-operating-proceduresfr ) the accept button, when clicked, greys out for a second or two, then comes back. The request is not accepted and there is the following error message displayed: 

"Users cannot join a sub-group if they are not a member of the parent group"

![collab subgroup join error](https://user-images.githubusercontent.com/23527358/30648507-35beb63c-9dec-11e7-902e-7cad53657ea3.png)

The requester does not receive an error message advising that they must join the parent group first, they simply get a message stating the request is pending;

![collab subgroup join pending](https://user-images.githubusercontent.com/23527358/30652115-85c2e23a-9df5-11e7-8f83-682715584a49.png)

Group settings seem to differ from what we see in GCconnex which may be a reason why this is happening.  GCcollab does not offer the option "Who can see this Group";

GCcollab:

![collab subgroup settings](https://user-images.githubusercontent.com/23527358/30652256-f2f06328-9df5-11e7-829a-4e8db7583c80.PNG)

GCconnex:

![connex subgroup settings](https://user-images.githubusercontent.com/23527358/30652270-fb233b06-9df5-11e7-9878-29e0dafa06b0.PNG)

**Comment by markwooff** [comment]
This will be updated as part of the latest code push happening over the weekend. On dev (https://dev.gccollab.ca/groups/edit/1245190), you can see the added option for Groups is now there:

![image](https://user-images.githubusercontent.com/5591488/30749724-45950042-9f82-11e7-98fd-3b65642719f3.png)
