### ISSUE TITLE
Block SMTP on Dev Server

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#21]
Need to block the SMTP port on the dev server so it doesn't send emails when testing.

**Comment by markwooff** [comment]
SMTP was set up to be blocked on the the development environment.

**Comment by sdkibb** [comment]
OK, I'll test by sending you an direct message. LMK if you get it. 

Don't post server port config on the GH.

**Comment by markwooff** [comment]
Ah yes, forgot we're not working on a private repo here. Thanks.

Haven't received any emails re: a direct message.

**Comment by sdkibb** [comment]
OK, then we're all set.
