### ISSUE TITLE
Contact uis page can only be accessed if logged in to GCcollab

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gccollab#215]
As a user who is having issues logging in or registering to GCcollab, I need to be able to access the Contact Us page without being logged in, so that I can reach the help desk. Thanks!
![contact us access collab](https://user-images.githubusercontent.com/15378977/31014987-b765eae2-a4eb-11e7-88c3-406bdc2834c3.JPG)

**Comment by LemieuxGen** [comment]
@markwooff I believe this bug was fixed a couple of weeks ago, but came back....

**Comment by markwooff** [comment]
Are you trying to access the new `Help / Contact Us` page at https://gccollab.ca/help/knowledgebase/? You should be able to visit this page without being logged in, just tested this.

**Comment by LemieuxGen** [comment]
Yes, that's the page. I checked again, and you're right. I can access it using the link from the top nav bar, from the link in the footer. However, I can't access it using the purple feedback button.

**Comment by markwooff** [comment]
Ah yes that's also the case for me, turns out there was an extra slash in the url (`https://gccollab.ca//help/knowledgebase` instead of `https://gccollab.ca/help/knowledgebase/`). This has now been fixed! Thanks.
