### ISSUE TITLE
Buttons for Slider on main page aren't doing anything in Chrome

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#217]
The buttons for the slider on the main page (left arrow, right arrow and the dots along the bottom) do not do anything. I'm using Chrome at TBS (so it's pretty locked down) and they work fine in IE.

Linked to https://github.com/Phanoix/gccollab-help/issues/4

**Comment by markwooff** [comment]
I'm unable to reproduce this error on both Chrome & IE. This happens for you on your TBS Chrome?

**Comment by markwooff** [comment]
@klecuyer happy to tell you that this issue has now been fixed!

**Comment by klecuyer** [comment]
@markwooff amazing. Thank you

**Comment by klecuyer** [comment]
@markwooff should i have closed this? I know it's fixed just likely not 'live' yet? Still not responsive in Chrome but I just realized that was only 12 minutes ago..

**Comment by markwooff** [comment]
@klecuyer it's live on GCcollab but you might have to give the page a "hard refresh" by pressing Ctrl + F5.
