### ISSUE TITLE
Issues when opting-in to Opportunities Platform

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gccollab#218]
When opting in to the opportunities platform (OP), I am only able to opt-in from the [OP page](https://gccollab.ca/missions/main) if I select "casual" or "Mentoring" for the type of opportunity I want to participate in. If I choose "Student integration" or "Collaboration", it saves, but brings me back to the OP page with the text telling me I need to Opt-in. 
![op opt-in](https://user-images.githubusercontent.com/15378977/31622267-fd69639e-b269-11e7-9010-4f3053b7f5d6.PNG)

Note, the options are saving in my profile (when opting in to "Students" and "Collaboration").
![op opt-in_profile](https://user-images.githubusercontent.com/15378977/31622334-21ac52b6-b26a-11e7-9997-bfc8dc6f38a3.PNG)

**Comment by markwooff** [comment]
Are you able to Opt In to the "Students" and "Collaboration" fields from your Profile page? (i.e. clicking Edit on your second screenshot).

I just tested the Opt In from the OP page with a new user account and was able to select Yes for all the Opt In options. Screenshot of the profile page shows the selections:

![image](https://user-images.githubusercontent.com/5591488/31624613-45b769be-b271-11e7-8487-360cf9314e3c.png)

**Comment by LemieuxGen** [comment]
I just tested again, and the behaviour is the same regardless of where I opt-in (OP page or Profile). I am able to opt-in if I select all (casual, student, mentor and collab) opt-in options, but if I only want to select Students and/or Collaboration (without selecting the "Casual" or "mentor"), it doesn't let me go past the "Opt-in to Opportunities Platform page".

**Comment by markwooff** [comment]
Thanks for clarifying this @LemieuxGen, this issue has been fixed. The Opportunities Platform will now recognize that you've opted in to one of the new opportunity types.

**Comment by markwooff** [comment]
@LemieuxGen if you could confirm this issue no longer exists, we can close issue. Thanks!
