### ISSUE TITLE
Unable to land on closed groups to request membership or accept invitation

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#219]
As a user, I cannot land on a closed group until I am a member. I can't see it in other people's groups either. The status is set to Closed- users must request to join but users who are not yet a member can't land.

Link to one example: https://gccollab.ca/groups/profile/144826/encra-ontario-region-student-ambassadorsfr
![image](https://user-images.githubusercontent.com/29754185/31725577-ae16a006-b3f2-11e7-92e9-b74b01d5d6e6.png)

This is also a prominent issue in GCconnex, for more details: https://github.com/gctools-outilsgc/gcconnex/issues/1424

**Comment by markwooff** [comment]
@klecuyer I've just put in a quick fix for users who have already been invited to Groups that they cannot see. For example, if you've been invited to the Group you referenced above, then visiting https://gccollab.ca/groups/profile/144826/encra-ontario-region-student-ambassadorsfr will now bring you to your Group Invitations page. This will allow the user to approve the invitation quickly.

I know this doesn't address the entire issue, but this should help for now at least.

**Comment by markwooff** [comment]
As mentioned in today's sprint review, a quick line of code was added to redirect users to their Group Invitations page if they're trying to land on a Group page they've already been invited to. Quick fix that could help with users that don't know where this page exists.

**Comment by LemieuxGen** [comment]
@markwooff do you know if this has been done in GCconnex as well?

**Comment by markwooff** [comment]
@LemieuxGen the code has been placed so that it would affect both GCcollab and GCconnex. So yes, just needs to be placed onto production!

**Comment by LemieuxGen** [comment]
@markwooff Great, thanks.
