### ISSUE TITLE
Email Text Needs Cleaning up

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#22]
Originally we dimmed down the email html due to email blocking issues. I don't think HTML was ever the issue with that. We should compare GCconnex email text to GCcollab and revert back to original format. This may include some changes in the emailing functionality itself (not just the text) that sent the email in text only formatting.

**Comment by markwooff** [comment]
Happen to know which emails would be affected by this? If not, I can just do a compare and take a look. Will have to find where the email templates are stored.

**Comment by markwooff** [comment]
The Elgg emailer function is located in `GCcollab/engine/lib/notification.php` on line 593. You'll notice that it is set to send emails out as plain text by default:

```
$headers = array(
	"Content-Type" => "text/plain; charset=UTF-8; format=flowed",
	"MIME-Version" => "1.0",
	"Content-Transfer-Encoding" => "8bit",
);
```

We could always add a new function that changes the `Content-Type` to `text/html` to allow for HTML emailers. Thoughts?

**Comment by sdkibb** [comment]
Compare the files to GCconnex. We had it changed to do plaint text because of email ftering but I don't think that was ever the issue. We should revert back to HTML and clean them up even further so they look good.

**Comment by markwooff** [comment]
Are you sure it was done in the code? Couldn't find any commits related to email functionality.

I did see that there is a deactivated plugin called **HTML Email Handler 3.1** in the backend, possible that it was used and then dropped after your email filtering issue?

**Comment by sdkibb** [comment]
Not sure but it must have been. I think you'll have to compare the code directly. Not sure if GCconnex ever really updated the file and GCcollab started with a snapshot to release.

**Comment by markwooff** [comment]
Was able to get the HTML emails working again, but it required some modifications of the **HTML Email Handler 3.1** plugin to correctly use the `Content-Type` of `text/html`. Emails would appear as it does in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/5591488/21552035/c35b0e1e-cdcc-11e6-87c8-9379777fe106.png)

**Comment by markwooff** [comment]
Closing issue as HTML emailers have been enabled for GCcollab with 69228878d34ef67b07718223f256e041e6072d75.
