### ISSUE TITLE
Open Group defaults 'Who can see this group' to 'Group members only'

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#224]
As a user, I want an open group. Anyone can see it, and anyone can join.

When editing my group settings, I can save it as an Open Group, however under Who can see this group? I want to select: 'All members logged into GCcollab', but when I click save and refresh the page or go back into my group settings, this is back to 'Group members only'
![image](https://user-images.githubusercontent.com/29754185/31962714-525d0686-b8cc-11e7-807c-3cec180aaf6b.png)

Link to the group: https://gccollab.ca/groups/profile/155003/endigital-academyfr

Linked to https://github.com/Phanoix/gccollab-help/issues/8

(in my non-admin account) I can see the group but no group content:
![image](https://user-images.githubusercontent.com/29754185/31962802-8fcf503c-b8cc-11e7-94b8-9ac34044e18f.png)

Users want the option to have a fully open group.

**Comment by markwooff** [comment]
This issue should now be fixed. @klecuyer could you confirm before I close the issue?

**Comment by klecuyer** [comment]
@markwooff confirmed. Close it
