### ISSUE TITLE
Federal Government Organizations to Add to department list/drop down

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#226]
- "Parliamentary Protective Service (PPS)" (@pps-spp.parl.gc.ca)

- Canadian Forces Liaison Council

**Comment by klecuyer** [comment]
Linked to https://github.com/gctools-outilsgc/gcconnex/issues/1278

**Comment by markwooff** [comment]
@JOutram77 got this one?

**Comment by markwooff** [comment]
@JOutram77 can we close this issue?

**Comment by JOutram77** [comment]
I have added the Parliamentary Protective Service to the list of Fed orgs in the registration, but we're not able to add Canadian Forces Liaison Council (CFLC) to the list. Despite the name, the CFLC is not a federal organization.
