### ISSUE TITLE
Opportunity posted shows irregular text box (s)

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#227]
Please see Opportunity here: https://gccollab.ca/missions/view/189035

Where we read "En tant que premier point de contact" and below "Si vous êtes intéressé, veuillez soumettre" are each in individual text boxes with scroll bars.

Is this something the user pressed in the WYSIWYG editor? Looks normal to me but just mid-text it displays these boxes.
![image](https://user-images.githubusercontent.com/29754185/32614678-c5ef7932-c53b-11e7-9180-72391877ab06.png)

I'm using Chrome..

Looking at the Source, this is the only thing that looks irregular to me from the rest of the text(?), but I also don't speak code..
yet.

![image](https://user-images.githubusercontent.com/29754185/32614896-42ff7f58-c53c-11e7-80da-4e5375362370.png)

**Comment by klecuyer** [comment]
If this is a user error, is there anything we can communicate with them to make this clearer next time?

**Comment by klecuyer** [comment]
Linked to https://github.com/Phanoix/gccollab-help/issues/15

**Comment by markwooff** [comment]
@klecuyer the `<pre>` tags in the code displays text in this "preformatted" text view. This is usually best when trying to display code in a viewable way, not so great for regular text.

I'm not sure how these were placed into the text, but I would let the user know that they can remove any `<pre>` or `</pre>` tags to remove this formatting.
