### ISSUE TITLE
Favicon Udpate

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#23]
The favicon in the root and the header code is set to:

http://gccollabdev.canadaeast.cloudapp.azure.com/_graphics/favicon.ico

But the code overrides it her:

<link href="http://gccollabdev.canadaeast.cloudapp.azure.com/mod/wet4/graphics/favicon.ico" rel="icon" type="image/x-icon" />

This should be removed or the wet4 graphic updated. I think it's easier to update the graphic with the cross coding being done between GCcollab and GCconnex.

**Comment by markwooff** [comment]
Removed previous GCconnex favicon and replaced with GCcollab favicon:

![image](https://cloud.githubusercontent.com/assets/5591488/21648751/0779a1a6-d26d-11e6-81a4-0db11b70b8b2.png)
