### ISSUE TITLE
Changes to GCcollab Registration page

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gccollab#235]
On GCcollab registration page, when a user selects an option from the “Occupation” drop down list that is not part of the approved groups (federal, provincial, municipal public servants, academics, students), a warning message (box) should appear below the “Occupation” field saying the following:
ENGLISH:
Individuals from this occupation need to be invited by an existing GCcollab member to register for an account. After receiving your invitation, register using the same email address that was used to invite you.
FRENCH:
Les individus de cette occupation doivent être invités par un membre existant de GCcollab pour s'inscrire à un compte. Après avoir reçu votre invitation, inscrivez-vous en utilisant la même adresse courriel que celle qui a été utilisée pour vous inviter.

**Change to Display name field:** 
Change “Display Name” to “Full Name” 
FRENCH: change “Non à afficher” to “Nom au complet”

**Change to text that appears to the left of the registration form**
bold (or stars) is used to identify the change the text - adding municipal.
ENGLISH
In section '"Who can register?"
- Canadian public servants (federal, provincial**, territorial and municipal**) can register by using their government email addresses.

FRENCH
In section "Qui peut s'inscrire?"

- Les fonctionnaires canadiens (fédéraux, provinciaux**, territoriaux et municipaux**) peuvent s'inscrire en se servant de leurs adresses courriel gouvernementales.

**Comment by LemieuxGen** [comment]
@markwooff sorry for the delay in getting this to you. Based on our conversation from yesterday with @JOutram77 here are the changes to the registration page. Let me know if you need further details, or clarification. Thanks.

**Comment by markwooff** [comment]
No worries @LemieuxGen - was able to get this in before the end of the sprint. Changes are live on GCcollab!

**Comment by JOutram77** [comment]
Can we also make similar changes to the Log In page at: https://gccollab.ca/login ?? @LemieuxGen can I get your approval on the following text before Mark makes these changes?

ENGLISH: 
A collaborative and networking space open to all Canadian public servants (federal, provincial**, territorial and municipal**), academics and students, as well as to all Canadians by invitation. Join the conversation!

FRENCH:
Un espace de collaboration et de réseautage ouvert à tous les fonctionnaires canadiens (fédéraux, provinciaux **, territoriaux et municipaux**), universitaires et étudiants, ainsi qu'à tous les Canadiens et à toutes les Canadiennes, par invitation. Prenez part à la conversation!

**Comment by markwooff** [comment]
@LemieuxGen I think this would make sense to also change on Login page. Thoughts?

**Comment by LemieuxGen** [comment]
@markwooff @JOutram77 Absolutely! Sorry, my bad that I forgot to include this as part of the language change - was trying to get it done before end of sprint too fast... Yes, text looks great. thanks!

**Comment by markwooff** [comment]
Great thanks @LemieuxGen! Text is in place, closing issue.
