### ISSUE TITLE
Link to validate new (external) e-mail address redirects to login page

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#236]
When I go to update my email address from my government email address to my personal email address via Account Settings and change it for one that is not white listed I get a pop up that states that an email was sent to the new email address for validation. 

I only received this pop-up after trying to change my email address for the third time - before the pop-up the window would simply look like it would refresh with the same original email address.

When I verified my email for the validation link and clicked it, I was brought to the Login page.

I could not login with the new email address.  I could login with the original email address or username.  once logged in, the email address was not updated.

NOTE: When performing this task on a users profile using an Admin account, a validation email is not sent and the change is saved immediately.

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gccollab-help/issues/19

**Comment by KevinChagnon** [comment]
@sdkibb

**Comment by markwooff** [comment]
Curious to see what this issue is @KevinChagnon since just tested yesterday without issue.

**Comment by markwooff** [comment]
@KevinChagnon is this still an issue?

**Comment by KevinChagnon** [comment]
I can no longer replicate this issue.  Closing ticket
