### ISSUE TITLE
Unable to Register - Canadian Tourism Commission

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#237]
The Canada Council for the Arts 

-Under Federal Government drop down
-Not in the domain manager

canadacouncil.ca
conseildesarts.ca

Should or Shouldn't they be white listed?

**Comment by KevinChagnon** [comment]
@JOutram77 
@klecuyer

**Comment by KevinChagnon** [comment]
**Fresh desk Tickets:**

https://support.gctools-outilsgc.ca/helpdesk/tickets/987

**Comment by JOutram77** [comment]
This organization has been added to GCcollab for open registration.
@KevinChagnon
