### ISSUE TITLE
GCcollab Registration: GC Centre for Disease Control

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#239]
Freshdesk ticket: https://support.gctools-outilsgc.ca/helpdesk/tickets/1013

@JOutram77 @KevinChagnon 

BC Centre for Disease Control affiliated with the University of British Columbia but is managed/funded by the Provincial Health Services Authority of BC.

email @bccdc.ca

**Comment by KevinChagnon** [comment]
@CPoulin1  @LemieuxGen

**Comment by JOutram77** [comment]
BC Centre for Disease Control (*.bccdc.ca) was added to both the domain manager and the registration.
