### ISSUE TITLE
Default to Receive Emails on Group

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#24]
Joy suggested we default group notification emails to on. If someone is part of a group would they want emails be default or would we rather an opt-in? I'd vote for opt-out.

**Comment by sdkibb** [comment]
Opt-Out decided.

**Comment by ToferC** [comment]
Good. Thanks! Need to let people know when stuff is happening.

**Comment by markwooff** [comment]
I've set the group notifications to be `on` by default. Any new users that join a group will have the email notifications checked.

Any users that are already in a group will keep the settings they previously had.
