### ISSUE TITLE
Registration GCcollab: Cégep de l'Outaouais

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#241]
https://support.gctools-outilsgc.ca/helpdesk/tickets/1400

All the other Cégeps are there, except this one. I suspect it might be an error, and not require any further research (hopefully a quick fix), but let me know.

@JOutram77 @KevinChagnon

**Comment by klecuyer** [comment]
@markwooff is this just a mistake that the cégep de l'outaouais is the only cégep not included? Is this an easy add?

**Comment by markwooff** [comment]
It would be an easy add from the admin panel, not sure why it wasn't added already! @JOutram77

**Comment by klecuyer** [comment]
@markwooff @CPoulin1 @LemieuxGen @JOutram77 @KevinChagnon Do we have the business decision to go ahead with adding Cégep de l'Outaouais? How soon can we get this added to the domain manager? Students looking to join for Winter 2018 semester.

**Comment by markwooff** [comment]
I've gone ahead and added the **Cégep de l'Outaouais** into the College dropdown in the GCcollab register page:

![image](https://user-images.githubusercontent.com/5591488/34115076-868429a8-e3e2-11e7-9349-3328b62a0c57.png)

**Comment by klecuyer** [comment]
Awesome @markwooff will their emails be okay to register? Can I close this issue?

**Comment by markwooff** [comment]
Yup, as long as their email is a **cegepoutaouais.qc.ca** email address. Closing issue.
