### ISSUE TITLE
Group invitations are missing group name and sender name in the email content

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#242]
See screenshot:
![image](https://user-images.githubusercontent.com/29754185/33783422-bbfa48ac-dc2a-11e7-9820-bf54d6d3102a.png)

The title of the email displays the sender's name and the name of the group, but the content does not.

![image](https://user-images.githubusercontent.com/29754185/33783492-0a3ed65e-dc2b-11e7-9c5a-82f1df0a44a8.png)

**Comment by markwooff** [comment]
@klecuyer this should now be fixed with the latest code push over the weekend. Please confirm and close the issue 👍

**Comment by Steph4104** [comment]
@klecuyer can you confirm if it still a issue. I just test on prod and everithing is fine.

**Comment by klecuyer** [comment]
@Steph4104 yes just tested it. Closing the issue
