### ISSUE TITLE
Not receiving invitations to join a group

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#243]
Erin is trying to invite me to join the GCcollab Student Ambassador group. I did not receive an invitation notification either in site or by email. 
Erin invited Joy and Joy did not get a notification. 
Then Admin.Joy invited Joy and Joy did not get a notification. 
Joy requested membership and is waiting to hear if Rima or Erin received notifications.

**Comment by markwooff** [comment]
Looking into it now, thanks @joymosk

**Comment by markwooff** [comment]
Was an issue with SMTP provider, should no longer be an issue.
