### ISSUE TITLE
Plus symbol (+) becomes blank space on The Wire 

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#245]
As a regular user, I would require the symbols that I enter in a Wire post to appear as entered;

The Wire replaces the plus character with a blank:

![image](https://user-images.githubusercontent.com/23527358/34117747-a3a4a0be-e3ea-11e7-82d4-3045cccd089a.png)

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gccollab-help/issues/20

**Comment by markwooff** [comment]
This is a strange issue, I can see that the `1 + 1=2` is saved in the database but it is not appearing properly on The Wire. Needs further investigation.

**Comment by markwooff** [comment]
The issue has now been fixed, the plus symbol should now appear correctly.
