### ISSUE TITLE
"Add this event to group" feature from GCconnex missing on GCcollab

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#246]
![capture](https://user-images.githubusercontent.com/24227707/34173539-c08d3194-e4c3-11e7-8eee-43352610e1b1.JPG)
This feature on GCconnex allows a group owner to add an event already posted to their group. I would like to be able to share the links to the GCcollab information sessions.

**Comment by markwooff** [comment]
As an admin, I went to your new event here: https://gccollab.ca/event_calendar/view/254458/engccollab-information-session-englishfrsu00e9ances-dinformation-sur-gccollab-anglais and can see the "Add to group" button:

![image](https://user-images.githubusercontent.com/5591488/34176124-d24e6188-e4cc-11e7-85e0-461109abd559.png)

Is this not appearing for you?

**Comment by markwooff** [comment]
It also appears that you aren't a group owner on GCcollab.. possibly just a group operator. That could be the reason the "Add to group" button is not appearing for you.

**Comment by markwooff** [comment]
Can we close this issue @joymosk ?
