### ISSUE TITLE
Registration - John Abbott College 

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#247]
emails ending in @johnabbottcollege.net
http://www.johnabbott.qc.ca/

@JOutram77 @CPoulin1

**Comment by klecuyer** [comment]
https://support.gctools-outilsgc.ca/a/tickets/1555

@KevinChagnon

**Comment by JOutram77** [comment]
The email domain *.johnabbottcollege.net has been added to the domain manager and registration for GCCollab. This domain is specific for students of the college.
