### ISSUE TITLE
GCcollab Validation email mentions GCconnex in French text

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#249]
Linked to https://github.com/Phanoix/gccollab-help/issues/21

There is a typo in the validation email. Where it says GCconnex in the French text, it should say GCcollab:
![image](https://user-images.githubusercontent.com/29754185/34890401-bd20c284-f79f-11e7-9c5d-8d6a5dfeb133.png)

**Comment by markwooff** [comment]
Thanks for bringing this issue up @klecuyer, error in the French email template. This has now been fixed.

**Comment by klecuyer** [comment]
@markwooff can I close this and alert the user?

**Comment by markwooff** [comment]
@klecuyer yes, thanks!
