### ISSUE TITLE
Onboarding Group Width (Mobile)

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#25]
The width of the text in the test group needs to be corrected for mobile view. It goes over the screen.

**Comment by markwooff** [comment]
The "Welcome to GCcollab Groups" modal was being cut off on mobile (as shown below):

![image](https://cloud.githubusercontent.com/assets/5591488/21524275/feddaf54-cce2-11e6-8c65-88b960f69224.png)

Updated the CSS in fe82e8c740b5e8bd8b227d5c052c363381ffdb37 to reduce the max-width on mobile devices.
