### ISSUE TITLE
Registration: Free Agents

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#251]
Federal government users who are Free Agents are forced to select an organization that they don't necessarily work for or currently work for. They have requested having their own selection as a Free Agent.

User's post: 
_Hello GCCollab!
 
I am part of Canada's Free Agents and I was wondering, since Free Agents are not exactly part of our host organizations, in my case Transport, would it be possible to have an additional field for those of us who are Free Agents called, you guessed it, Free Agent. The reason being is that soon we will have 60 Free Agents in the Public Service hosted by three departments working is dozens host organizations. We, by design, don't fit the mold. So how about it? Add a Free agent organization?
 
Ryan Sigouin_

**Comment by klecuyer** [comment]
@JOutram77 @KevinChagnon 
Freshdesk ticket: https://support.gctools-outilsgc.ca/helpdesk/tickets/1732

**Comment by KevinChagnon** [comment]
Colin was invited to the platform via a group invitation as seen here:
https://gccollab.ca/groups/requests/97886/email_invites

**Comment by KevinChagnon** [comment]
@markwooff

**Comment by markwooff** [comment]
@KevinChagnon this user's name is Ryan Sigouin and he already has an account. Wrong ticket?

**Comment by JOutram77** [comment]
We are looking into revising our policy so users can identify their organization as a funded functional community, eg. Free Agents, Communications Community Office (CCO). et al. I'll be sure to share the decision here. Stay tuned!

**Comment by JOutram77** [comment]
A decision has been made...functional communities will not be added to the list of federal organizations from which users can choose identify.

@klecuyer can you let Ryan Sigouin know and then close this ticket. Thanks - J

**Comment by KevinChagnon** [comment]
@markwooff - yes, it was the wrong ticket.
