### ISSUE TITLE
Users able to (accidentally) delete their own groups in the Related Groups widget

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#252]
Question: Is there absolutely any way to restore a group (two groups) once they've been deleted?

This is the user story: As a user trying to configure my related groups and related groups widget, instead of clicking the delete icon to delete the link in the widget, I accidentally deleted the entire group and its sub-group.

From a user perspective, it's easy to see how the Related Groups displayed in the widget could be misinterpreted. The user accidentally deleted two groups (a group and its sub) by clicking this icon:

![image](https://user-images.githubusercontent.com/29754185/35067427-da7c6666-fba1-11e7-9536-3d91aaa4ddcf.png)

There were three groups, each sub-groups of the other:

1. Open Government Group https://gccollab.ca/groups/profile/18873/enopen-governmentfr
2. (sub-group) Intergovernmental Collaboration *deleted*
3. (sub-sub-group) Canada Open Government (COG) *deleted*

Question: is there any way to restore his two groups?
If not, how can we change this or enhance the UI so that users aren't accidentally deleting groups when configuring widgets.

**Comment by klecuyer** [comment]
Linked to https://github.com/Phanoix/gccollab-help/issues/22

**Comment by markwooff** [comment]
Unfortunately there is no way to recover a group that has been deleted. There is a prevention method in place in the UI for all delete buttons with a prompt asking **"Are you sure you really want to delete this?"** so this sounds like an unfortunate user error.

**Comment by klecuyer** [comment]
@markwooff is there any easy(ier) way to transfer files from a person to a group? When deleting the group, all the group files transferred to a colleague's profile, which is fine. Just now that he's recreated it, is there any way to get mass files into a group other than deleting and reuploading them? Thanks! https://gccollab.ca/file/owner/Moses.Iziomon

**Comment by markwooff** [comment]
@Phanoix I imagine this could be done by manually changing the `owner_guid` of these files in the database. Do you know if there would be any issues by changing it this way?

**Comment by klecuyer** [comment]
The group we'd like all the files on Moses' profile to go to is: https://gccollab.ca/groups/profile/304959/encanada-open-government-working-group-cogwgfrgroup-de-travail-sur-le-gouvernement-ouvert-du-canada-gtgoc

**Comment by klecuyer** [comment]
@Phanoix @markwooff is there any way we can do this? Is it easy enough to do?

**Comment by markwooff** [comment]
@klecuyer can we close this?

**Comment by klecuyer** [comment]
Yes

**Comment by klecuyer** [comment]
This is also in GCconnex and group operators can delete the group. It should only be the group owner.
