### ISSUE TITLE
No "search" function on Mobile App

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gccollab#253]
When using the GCcollab mobile app on android, there seems to be no search function. I haven't been able to find it anywhere -  would be good to have it visible on the landing page or in the hamburger menu.

**Comment by sdkibb** [comment]
Hi Rick, you're right there isn't one at this time. IT would be a nice feature but not sure when it will be included at this point.

**Comment by massierick** [comment]
Thanks for the info Sean! I wasn't sure if maybe it was just user error/nav error.

**Comment by markwooff** [comment]
Hi @massierick , we've separated the mobile application code into a new repo. I've cloned this issue there so we can track it (https://github.com/gctools-outilsgc/gccollab-mobile/issues/50). Closing this issue, thanks!
