### ISSUE TITLE
Error Messages when accessing My Colleagues

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#254]
Linked to https://github.com/Phanoix/gccollab-help/issues/23

This user has added 2000+ colleagues on GCcollab. Now when he visits his **Colleague Requests** he gets an error:

https://gccollab.ca/friend_request/Justin.Patrick

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 78 bytes) in /var/www/html/gccollab/engine/classes/Elgg/Database.php on line 351

**Comment by klecuyer** [comment]
@bmrgould @sdkibb Is this temporary fix live yet? Just tried accessing his requests with error: https://gccollab.ca/friend_request/Justin.Patrick Thanks!

**Comment by sdkibb** [comment]
It was overwritten on the weekend, it'll be back up shortly.

**Comment by markwooff** [comment]
@klecuyer I've placed their changes back on the site, the temporary fix should be in.

**Comment by bmrgould** [comment]
Fixed. Added pagination to the /friend_request/ page.
