### ISSUE TITLE
Registration: Sheridan College

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#256]
https://www.sheridancollege.ca/

Sheridan College would like to be added to the list approved to register for GCcollab.

**Comment by klecuyer** [comment]
https://support.gctools-outilsgc.ca/helpdesk/tickets/1830

**Comment by klecuyer** [comment]
@KevinChagnon @JOutram77 @CPoulin1

**Comment by JOutram77** [comment]
Sheridan College has been added to the domain manager and registration.

@klecuyer can you inform the user and close the ticket. Thanks

**Comment by klecuyer** [comment]
@JOutram77  is there a delay in when this will be visible to people registering? Sheridan College is not currently available in the dropdown list

**Comment by JOutram77** [comment]
Sheridan College is in there.
