### ISSUE TITLE
Body of message replaced with strange coding/text

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#258]
As a user sending a private message on GCcollab, my message body text displays as: cp_notify:body_site_msg:description

The actual body of the text is lost.

![image](https://user-images.githubusercontent.com/29754185/35342809-fa4a122c-00f6-11e8-9e7d-41e4432dee5a.png)
![image](https://user-images.githubusercontent.com/29754185/35342850-177f864c-00f7-11e8-856b-0d6d6d9acb0e.png)
@KevinChagnon @LemieuxGen @JOutram77 @markwooff

**Comment by markwooff** [comment]
Is this no longer an issue that it was closed?

**Comment by klecuyer** [comment]
@markwooff I closed the issue juuuuust after I created it cause Jeff told me you were already working on a quick fix. I just tested messages and the issue seems to be resolved, but can you close this when it's for sure fixed? Sorry next time I'll leave it open

**Comment by markwooff** [comment]
@klecuyer gotcha. A quick fix was put in yesterday so I will close the issue.
