### ISSUE TITLE
Onboarding - Job title not updating

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#26]
When you put in a job title it updates the work experience but not your actual title.

**Comment by markwooff** [comment]
Issue was fixed with 6d1fb5ed019907bad6e6e3755cc6fa40eb8d1897. The updated logic will update the user's **Job Title** in their profile and leave the **Work Experience** alone.

Or did we want to update both?

**Comment by markwooff** [comment]
Closing as logic is working as it should.
