### ISSUE TITLE
Fatal Error when trying to e-mail all members (specific group)

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#260]
"As Group owner/Operator, I need to be able to use the "Email Members" feature without receiving a Fatal Error so that I can communicate with group members by email via a single message"

This is happening in a specific group:

https://gccollab.ca/groups/profile/217224/engroupe-de-travail-interministu00e9riel-prochains-outils-dapprovisionnement-de-formation-linguistique-interdepartmental-working-group-next-language-training-procurement-toolsfrgroupe-de-travail-interministu00e9riel-prochains-outils-dapprovisionnement-de-formation-linguistique-interdepartmental-working-group-next-language-training-procurement-tools

When the option "Email Members" i selected under "Settings" (or "Member") on the group page, I am presented with a fatal Error message: 

![image](https://user-images.githubusercontent.com/23527358/35405158-4620b21e-01d3-11e8-8b07-402744638f72.png)

I have tested this in other groups and do not get the same result when clicking "Email Members"

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gccollab-help/issues/26

**Comment by markwooff** [comment]
Issue should now be fixed on GCcollab. The code in question is shared with GCconnex so should fix any instances of this issue there as well.

**Comment by markwooff** [comment]
@KevinChagnon can we close?

**Comment by LemieuxGen** [comment]
@KevinChagnon Please confirm that the issue is fixed and if so, close the issue. Thanks!

**Comment by KevinChagnon** [comment]
Tested - issue resolved.

**Comment by KevinChagnon** [comment]
Note from client: "I thought my mail all group members problem was resolved. I was able to get to the input boxes, and to write a message, but when I went to send I once again got an error message. 
Andrea"

I am asking client if we can send a message to members on her behalf to test or if she can do it herself and send a screenshot of the error message.....

**Comment by KevinChagnon** [comment]
Comment added by customer Andrea.goffart in Freshdesk ticket id 1911:

The e-mail all members now works! Thanks!!! A.
