### ISSUE TITLE
missing option add an image to wire post when sharing opportunities from the OP

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gccollab#263]
On GCcollab, when sharing an opportunity from the OP on the Wire, the option to add an image to the wire post is missing. When sharing other types of content on the Wire (discussion, page, etc.) allows the user to post an image, but not when sharing an opportunity.

Sharing Opportunity on the wire: 
![gccollab_wire_no image sharing op](https://user-images.githubusercontent.com/15378977/35744478-75bb696a-080e-11e8-838b-4099cccc3958.PNG)

VS
Sharing other content on the wire
![gccollab_wire_add image sharing blog](https://user-images.githubusercontent.com/15378977/35744498-83f59b5e-080e-11e8-8a95-0d39dce49b93.PNG)

**Comment by markwooff** [comment]
Does this issue also appear on GCconnex? Might be that the OP code overrides the new image feature.

**Comment by LemieuxGen** [comment]
@markwooff just checked and it's the same on GCconnex. Sorry, should of verified. Do you want me to create a ticket in GCconnex as well?

**Comment by markwooff** [comment]
@LemieuxGen no worries, the fix for GCcollab would also fix GCconnex. A fix is in place on GCcollab, just waiting for the code to be merged into GCconnex 👍

**Comment by LemieuxGen** [comment]
awesome. Thanks @markwooff
