### ISSUE TITLE
JSON Appearing in GCcollab Content

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#266]
So far, JSON is appearing in GCcollab group invitations:
![image](https://user-images.githubusercontent.com/29754185/36042453-de3731dc-0d99-11e8-8171-d5206bd927ba.png)

I'll continue to add examples here as I find them.

**Comment by markwooff** [comment]
@klecuyer is this only on collab & not on connex as well?

**Comment by klecuyer** [comment]
@markwooff I have not yet seen it in GCconnex or had it reported in GCconnex

**Comment by markwooff** [comment]
@klecuyer great thanks. The fix should now be in GCcollab and will be brought into GCconnex on the next code push.

**Comment by klecuyer** [comment]
@markwooff I did just get a user reporting JSON in GCcollab breadcrumb trails. I have not yet seen this in GCconnex. I tested creating a GCconnex folder with french accents and didn't see any JSON:
![image](https://user-images.githubusercontent.com/29754185/36546305-1505245c-17b9-11e8-9749-80df358812c5.png)
link to where I found this: https://gccollab.ca/file/group/351620/all#378516

**Comment by markwooff** [comment]
@klecuyer this would only appear if looking at files within a folder or sub-folder. Should appear on GCconnex as well, but either way I've fixed the issue. Should now be fixed on GCcollab.

**Comment by klecuyer** [comment]
@markwooff thank you, closing now
