### ISSUE TITLE
Change French translation of 'Activity' in groups

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#267]
Update French translation of the word 'Activity' in groups:
![image](https://user-images.githubusercontent.com/29754185/36042805-12b4c342-0d9b-11e8-85ac-6d42e3dc1a0d.png)

**Comment by markwooff** [comment]
Same question.. is this just on collab?

**Comment by klecuyer** [comment]
No I just tested and it's on GCconnex also. The reason I was having a hard time testing is because in order to have 'Activity' show in the group menu, you have to disable almost every other group feature (polls, discussions, blogs, etc) @markwooff 

I just did this in GCconnex and can determine it's in connex as well.
![image](https://user-images.githubusercontent.com/29754185/36044053-63ad7092-0d9f-11e8-8b83-9d9bfab203c2.png)

**Comment by markwooff** [comment]
@klecuyer great thanks. The fix should now be in GCcollab and will be brought into GCconnex on the next code push.
