### ISSUE TITLE
Mobile App: Login Button not activating

### ISSUE THREAD

**Issue by CalvinRodo** [gctools-outilsgc/gccollab#268]
When pasting my password into the Mobile App the login button stays inactivate and I'm unable to login to my account. 

I'm copying from a password manager.

OS: Android 8.1.0
Device Pixel XL

**Comment by CalvinRodo** [comment]
This only happens when I paste my password before entering my username, if I paste my password then type in my email it works fine.

**Comment by sdkibb** [comment]
I just fixed and uploaded to the app stores. The release - 1.2 - should be up in a couple of hours on Google Play.

We actually have a separate closed repo for the app that I've been meaning to have ported over to our enterprise account where the change was implemented.
