### ISSUE TITLE
Mention of Protected A to be removed and changed to unclassified

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#269]
When a user goes to upload a file in GCcollab, there is a "Friendly reminder" indicating that the platform is limited to Protected A when in fact it is limited to unclassified information/documents;

![image](https://user-images.githubusercontent.com/23527358/36220622-473a65bc-1189-11e8-9ede-fa8dde2dd1a2.png)

The text "This means that only "unprotected", "unclassified" or "Protected A" document should be posted."
Should be modified to "This means that only unclassified document**s** should be posted."

In French: Cela signifie que seuls des documents non classifiés  peuvent être affichés.

We should also do a site-wide search for any other mention of Protect A (aside from it being mentioned in discussions/comments/blogs etc.) and replace it with "unclassified" ("non classifié(s)")

**Comment by KevinChagnon** [comment]
@markwooff @Steph4104

**Comment by markwooff** [comment]
@KevinChagnon text has been updated on GCcollab and is now live. Did a search for the term "Protected A" across the site and only appears in the text that would show for GCconnex 👍

**Comment by KevinChagnon** [comment]
Thanks!

**Comment by Steph4104** [comment]
@KevinChagnon , in Gccollab app we have this: For public servants, only material that is classified Protected A or below should be posted on the GC Tools. / Pour les fonctionnaires, seul le matériel classé Protégé A ou ayant une classification inférieure devrait être publié dans les outils du gouvernement du Canada.
Should we change it?

**Comment by KevinChagnon** [comment]
@Steph4104 the text should reflect the same text as seen in GCcollab (web);

"For federal public servants, only material that is unclassified should be posted on GCcollab."

"Pour les fonctionnaires, seul le matériel non classé devrait être publié dans GCcollab."

Please change.

c.c @LemieuxGen

**Comment by LemieuxGen** [comment]
Approved.
