### ISSUE TITLE
City of Delta (@delta.ca) to be white-listed

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#270]
"Invalid email" error when City of Delta (**@delta.ca**) tries to register an account.

This domain should be whitelisted.

http://www.delta.ca/

Helpdesk Reference: https://support.gctools-outilsgc.ca/helpdesk/tickets/2163

**Comment by KevinChagnon** [comment]
@markwooff

**Comment by markwooff** [comment]
I can see that the email of *.corp.delta.bc.ca exists in the system but not delta.ca - Jeff usually takes care of these but I can add it in if needed.

**Comment by KevinChagnon** [comment]
Yes please add @delta.ca

**Comment by KevinChagnon** [comment]
added *.delta.ca to GCcollab Domain manager.
