### ISSUE TITLE
City of Burlington (@burlington.ca) to be white-listed

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#271]
"Invalid email" error when City of Burlington (@burlington.ca) tries to register an account.

This domain should be whitelisted.

https://www.burlington.ca

https://support.gctools-outilsgc.ca/helpdesk/tickets/2167

**Comment by KevinChagnon** [comment]
@markwooff

**Comment by markwooff** [comment]
Similar situation here. I can see that "*.cms.burlington.ca" has been added to the whitelist but not "burlington.ca". Should I add this in as well?

**Comment by KevinChagnon** [comment]
Yes, please add @burlington.ca

**Comment by klecuyer** [comment]
edited the domain manager to *.burlington.ca so anything before that will be whitelisted @KevinChagnon if you want to reply to user and close Freshdesk ticket: https://support.gctools-outilsgc.ca/helpdesk/tickets/2167
