### ISSUE TITLE
Registration: Canada Deposit Insurance Corporation

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#272]
Organization is already in the federal drop-down but email domain needs to be added.
![image](https://user-images.githubusercontent.com/29754185/36269642-a3b31de8-1247-11e8-8b7a-2889cc9735b1.png)

Email is @cdic.ca

@KevinChagnon @JOutram77

**Comment by klecuyer** [comment]
@CPoulin1

**Comment by klecuyer** [comment]
@markwooff Chris P approved this, can we add it to the domain manager? If you want to train me on how to do this/give me rights, even while Jeff's away I can do it, after getting Chris' go-ahead

**Comment by markwooff** [comment]
@klecuyer that'd be great! If you wanted, I could show you & @KevinChagnon how to add new domains to the platform tomorrow morning. Saves the hassle of having to come to us every time a new domain has been approved for adding.

**Comment by KevinChagnon** [comment]
Was **@cdic.ca** added?

@markwooff Yes, a sit down to be shown how to add to the Domain manager would be great!

**Comment by markwooff** [comment]
@KevinChagnon CDIC has now been added, let's schedule a walkthrough of the Domain manager this week. Closing issue.
