### ISSUE TITLE
Remove iFrame option in WYSIWYG editor

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#273]
The GCcollab helpdesk received an inquiry related to the use of the iFrame option in the WYSIWYG editor stating that the function did not work properly.  After discussion with @markwooff it has been determined that this option should not have been included in the WYSIWYG editor and should be removed; due to both, technical and security reasons.

The same should be reflected in GCconnex.

**Comment by KevinChagnon** [comment]
![image](https://user-images.githubusercontent.com/23527358/36273186-b6b0c9d6-1251-11e8-9616-7bd0d5dbbff6.png)

**Comment by markwooff** [comment]
The iFrame button has now been removed from GCcollab, should also be removed from GCconnex once code is pushed over the weekend.

**Comment by KevinChagnon** [comment]
Thanks!
