### ISSUE TITLE
Registration: Federal Bridge Corporation

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#275]
Already in the list of federal entities:
![image](https://user-images.githubusercontent.com/29754185/36275851-0b4b41d0-125a-11e8-997f-77a1a5313fc7.png)

Emails need to be whitelisted: @federalbridge.ca

**Comment by klecuyer** [comment]
added to domain manager

**Comment by markwooff** [comment]
Thanks @klecuyer !
