### ISSUE TITLE
Create a button to join a group, inside each group

### ISSUE THREAD

**Issue by markwooff** [gctools-outilsgc/gccollab#28]
Pulled this issue from Taiga. It appears there was discussion on adding a new button that displays the **Join Group** option without having to go through the **Settings** dropdown.

**Comment by sdkibb** [comment]
Yes, this is big. One Click Join is what we we really want. This will also be ported over to GCconnex.

**Comment by markwooff** [comment]
Done. Can take a look at the Mental Health group on dev http://gccollabdev.canadaeast.cloudapp.azure.com/groups/profile/7065/mental-health-in-the-workplace to see how this looks.

If a user is currently not in the group, it will display "Join group". If they are already in the group, it will display "Leave group".

**Comment by sdkibb** [comment]
Looks great. A little rough on mobile but the whole thing does so it's not this change that did it. If we can clean up the mobile look I'm sure that's good. @Phanoix should see this and see if he wants to port this over to GCconnex.

**Comment by markwooff** [comment]
Good call, added a CSS media query for mobile on this to make it look better. But yes, all of the platform could use some mobile-friendliness tweaks.

**Comment by ToferC** [comment]
Can pls confirm that Join Group didn't already exist for non-admins? Currently, admits have both Join Group and Settings>Join Group. 

My understanding is that admits get settings while regular users just get join/leave group. Reference GCCONNEX.

**Comment by markwooff** [comment]
@ToferC Yes, originally all non-admins would see a "Join Group" button as seen in the screenshot below. Admins would actually have to go through Settings > Join Group to join.

![image](https://cloud.githubusercontent.com/assets/5591488/21873234/47f39d08-d83b-11e6-9103-6bd1f2004427.png)

Originally, both admins & non-admins would have previously had to navigate into Settings > Leave Group to leave it as seen in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/5591488/21873256/6831946c-d83b-11e6-8269-99cb6f3ce443.png)

This new code added a one-click option for non-admin users to leave the group:

![image](https://cloud.githubusercontent.com/assets/5591488/21873299/aba80a3c-d83b-11e6-84fc-4493b49e4d23.png)
