### ISSUE TITLE
Registration: Loto Quebec

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#282]
It looks like Technologies NTER (Loto-Quebec) was recently added to the domain manager.

![image](https://user-images.githubusercontent.com/29754185/36553771-3ad9c9e6-17cb-11e8-9694-a285566a9c7f.png)

 Apparently Technologies NTER is a subsidary of Loto Quebec. Can we also add the domain @loto-quebec.com

Société des loteries du Québec @loto-quebec.com

**Comment by markwooff** [comment]
Oh we had put in the domain of @lotoquebec.com, does the correct domain include the dash? Will fix after confirmation.

**Comment by klecuyer** [comment]
@markwooff I have made the change. Thanks!
