### ISSUE TITLE
GCcollab invitation email - change to help article link

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gccollab#286]
A link in the email notification sent to users invited to join a GCcollab group needs to be updated to point to the correct help article.

In English, link to "How to join a group" should link to: https://gccollab.gctools-outilsgc.ca/en/support/solutions/articles/2100030475-how-do-i-join-a-group-

In French, link to "Comment se joidre à un groupe?" should link to: https://gccollab.gctools-outilsgc.ca/fr/support/solutions/articles/2100030475-comment-se-joindre-%C3%A0-un-groupe-

![image](https://user-images.githubusercontent.com/15378977/36788157-dce59c90-1c5a-11e8-9039-78a51cb69c37.png)

**Comment by markwooff** [comment]
@LemieuxGen the link has been updated and is now live on production 👍

**Comment by LemieuxGen** [comment]
@markwooff You're awesome! thanks.
