### ISSUE TITLE
Registration: The Newfoundland and Labrador Centre for Health Information

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#288]
The Newfoundland and Labrador Centre for Health Information
Email: @nlchi.nl.ca
Web: https://www.nlchi.nl.ca/

@JOutram77 @KevinChagnon 

https://support.gctools-outilsgc.ca/helpdesk/tickets/2398

**Comment by klecuyer** [comment]
https://support.gctools-outilsgc.ca/helpdesk/tickets/2398

**Comment by JOutram77** [comment]
nlchi.nl.ca has been added to the GCcollab domain manager
