### ISSUE TITLE
Invalid reCaptcha

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#29]
The reCaptcha does not appear on the registration page of GCcollab.

An error is displayed saying "Invalid reCaptcha validation".

This is stopping users from registering for accounts to GCcollab.

**Comment by Phanoix** [comment]
@sdkibb should check the google side of it, maybe we need to do something there. If this persists you can temporarily disable the mod.

**Comment by markwooff** [comment]
Possible that the `Site key` and `Secret key` aren't valid anymore? Can renew and enter new ones from the Plugin settings.

I've disabled the **Elgg Recaptcha** mod in the meantime as we need the login creds for the Google account used to set up the recaptcha.

**Comment by markwooff** [comment]
@JOutram77 the reCaptcha appears to be working again, I've re-enabled the plugin.

**Comment by sdkibb** [comment]
Turns out it was code related. Fixed.
