### ISSUE TITLE
Registration: WoodGreen Community Services

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#292]
Institution/Organization/Business name: WoodGreen Community Services, Financial Empowerment Program

Email: @woodgreen.org

Context: 
I am a member of the Canada Learning Bond Champions Network.  At the annual meeting on February 6&7th in Toronto, we were all encouraged to join GCcollab.  I was instructed to register, and then access the Education Savings Incentives Resources page at https://gccollab.ca/profile/95754/
 
I’m the Manager of the Financial Empowerment Program at WoodGreen Community Services in Toronto (a charitable, community service organization).  I believe that you would qualify my agency as a “Non-Governmental Organization”.
 
Geographic Location (general): East Toronto, although clients do not have to live in East Toronto to receive services. 
 
@JOutram77

**Comment by JOutram77** [comment]
I don't believe we currently have the approval to allow this organization to be whitelisted in GCcollab. Suggest we reply to this user and close the issue.
