### ISSUE TITLE
Registration: First Nations Tax Commission

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#297]
Email: @fntc.ca

Web: http://fntc.ca/

User story: I am the records and information manager at the First Nations Tax Commission, an institution subject to federal Access to Information and Privacy laws, but not normally included under the definition of government institution. I would like to create an account for GCcollab, which I was informed would have some resources and a discussion forum for Access to Information and Privacy topics.

**Comment by klecuyer** [comment]
https://support.gctools-outilsgc.ca/helpdesk/tickets/2617

**Comment by JOutram77** [comment]
I don't believe we currently have the approval to allow this organization to be whitelisted in GCcollab. Suggest we relay to this user and close the issue.
