### ISSUE TITLE
Link to GCcollab page requiring login lands on home (sign in, log in)

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gccollab#300]
When visiting a page requiring sign into GCcollab:
https://gccollab.ca/docs/view/481358/why-gccollab-v800

After signing in, user lands on home page.
Should take user to requested page.

**Comment by markwooff** [comment]
@PhilAndrecheck this issue has been addressed, users will now be brought to the original URL they attempted to reach before logging in 👍
