### ISSUE TITLE
GCcollab profile avatars are distorted or removed since launch of Accounts service

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gccollab#301]
Following the release of the GCcollab Account service, the GCcollab profile avatar are now distorted.
- Avatars are stretched and oval shaped,
- some avatars have been removed and now show grey avatar.

The wonky oval avatars are due to the images coming from Accounts. If we rip off the band-aid and go back to Collab as the source of the avatars this will be fixed.

At the moment, if you set your avatar on Accounts it get's carried over to GCcollab.

Could be changed to tell GCcollab to disregard the avatar coming from Accounts and to use avatars from GCcollab profile avatars. This should only impact people who have registered for GCcollab since this Tuesday (due to a partial fix that was implemented on Tuesday.)
This will result in Collab users avatars reappearing but the few that registered since Tuesday that set their Avatars through Accounts will need to reset their avatar through Collab.

**Comment by LemieuxGen** [comment]
@markwooff @bryan-robitaille FYI - based on discussion re: avatars and accounts service. This should be fixed and pushed to production as soon as the fix is done. Thanks!

**Comment by markwooff** [comment]
@LemieuxGen fix has been pushed to production, discussing next steps.

**Comment by markwooff** [comment]
Issue has been fixed, avatars remain on GCcollab instead of Concierge for now. Will eventually be using Profile as a Service for all user profile information, including avatar. Closing issue.
