### ISSUE TITLE
Registration: HEC Montréal

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#305]
HEC Montréal is a French-language university institution offering internationally renowned management education and research.

http://www.hec.ca/en/

Emails @hec.ca

Freshdesk: https://support.gctools-outilsgc.ca/helpdesk/tickets/2847

**Comment by klecuyer** [comment]
https://support.gctools-outilsgc.ca/helpdesk/tickets/2847

**Comment by JOutram77** [comment]
Knowing this was previously in the domain manager/registration list, I compared the current domain manager list to my notes, there were 10 Canadian universities extensions missing. 

Now added include: enap.ca; etsmtl.ca; glendon.yorku.ca; hec.ca; inrs.ca; luthercollege.edu; polymtl.ca; rmc.ca; stmcollege.ca; unbc.ca
