### ISSUE TITLE
Bilingual changes to GCcollab Message

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#310]
Below are a few changes to be made to make GCcollab Message navigation bilingual for users.
_Ignore red boxes. Those are for help content, not for outlining these issues._

- When user initially visits https://message.gccollab.ca/ the login screen only displays in English right now. There is no language toggle. Text should read 'GCcollab Message' in English, 'Message GCcollab' in French.
![message1en](https://user-images.githubusercontent.com/29754185/38501788-c970f060-3bdb-11e8-9fd5-407eb8ae2892.PNG)

-  When a user is logging into their GCcollab account, with French settings, the top-left title still reads 'GCcollab Account'. It should say 'Compte GCcollab' (or other)
![message2fr](https://user-images.githubusercontent.com/29754185/38501927-1ce07342-3bdc-11e8-9308-80c8c9123613.PNG)

- Next page, same change. When authorizing GCcollab Message in French, the top left title should be changed from 'GCcollab Account' to 'Compte GCcollab'. In the text box asking you to authorize access, 'GCmessage' should also be changed to 'GCcollab Message' in English and 'Message GCcollab' in French.
![message3fr](https://user-images.githubusercontent.com/29754185/38502074-7b315b3c-3bdc-11e8-8682-544ef433bef2.PNG)

- GCcollab Message prompts the user to register a username. This page and message only appears in English and should have a language toggle. The user's language choice should 'stick' throughout the login process, or at least give them an option to toggle on each page.
![message4en](https://user-images.githubusercontent.com/29754185/38502259-eea53a70-3bdc-11e8-8c8a-497a85768bdf.PNG)

- Once the user has logged into GCcollab Message, the welcome message only appears in English. It should appear in French if the user has selected French settings, or just appear bilingually, regardless of user setting.
![message5fr](https://user-images.githubusercontent.com/29754185/38502340-1b0591fa-3bdd-11e8-97c9-adab78799ea7.PNG)

@LemieuxGen

**Comment by LemieuxGen** [comment]
@klecuyer Thanks for the detailed info. I removbed a few elements from the issue. Here's why...
Items removed: 
- Text should read 'GCcollab Message' in English, 'Message GCcollab' in French.
     - **_We haven't determined the official names, branding going forward. Let's leave it GCmessage for now and change it once we have a way forward._** 
- When a user is logging into their GCcollab account, with French settings, the top-left title still reads 'GCcollab Account'. It should say 'Compte GCcollab' (or other)
![message2fr](https://user-images.githubusercontent.com/29754185/38501927-1ce07342-3bdc-11e8-9308-80c8c9123613.PNG)
     _**- removing this element from this issue as there's already an issue for this in the concierge repo: https://github.com/gctools-outilsgc/concierge/issues/33**_ 

- Next page, same change. When authorizing GCcollab Message in French, the top left title should be changed from 'GCcollab Account' to 'Compte GCcollab'. In the text box asking you to authorize access, 'GCmessage' should also be changed to 'GCcollab Message' in English and 'Message GCcollab' in French.
![message3fr](https://user-images.githubusercontent.com/29754185/38502074-7b315b3c-3bdc-11e8-8682-544ef433bef2.PNG)
     _**- removing this element from this issue as there's already an issue for this in the concierge repo: https://github.com/gctools-outilsgc/concierge/issues/33
         - We haven't determined the official names, branding going forward. Let's leave it GCmessage for now and change it once we have a way forward**_

**Comment by LemieuxGen** [comment]
@klecuyer could you add in the French terminology required for the update?

**Comment by klecuyer** [comment]
@LemieuxGen 
I've gone through and it looks like these changes are already done in French. Checkboxes for what's done/not done.

_When user initially visits https://message.gccollab.ca/ the login screen only displays in English right now. Needs a language toggle._ 
Text to revise for French:
- [x] Connectez-vous avec votre compte GCcollab
- [x] En procédant, vous acceptez nos Conditions d'Utilisation et notre Politique de confidentialité.
- [x] Propulsé par la plate-forme de discussion de code source ouvert Rocket.Chat.
![image](https://user-images.githubusercontent.com/29754185/39190881-88eea3ba-47a3-11e8-9b41-6a47fd3c7d02.png)


_GCcollab Message prompts the user to register a username. This page and message only appears in English and should have a language toggle. The user's language choice should 'stick' throughout the login process, or at least give them an option to toggle on each page._ 
**This is what I can't seem to verify if this screen is changed or not. I seem to have created GCcollab Message accounts previously for every email instance I own, so I no longer get asked to choose a username when re-registering these accounts. @markwooff do you know if this screen is updated to include French text when the user selects French settings?**

Text for French:
- [ ] Enregistrer le nom d'utilisateur
- [ ] Ce nom d'utilisateur est utilisé pour permettre aux autres de vous mentionner dans les messages.
- [ ] Nom d'utilisateur
- [ ] Utilisez ce nom d'utilisateur
![image](https://user-images.githubusercontent.com/29754185/39189644-b29cb5ec-47a0-11e8-8bcc-e8f4a2d67c27.png)


_Once the user has logged into GCcollab Message, the welcome message only appears in English. It should appear in French if the user has selected French settings, or just appear bilingually, regardless of user setting._
- [x] Bienvenue sur GCcollab Message!
![image](https://user-images.githubusercontent.com/29754185/39191135-377304ee-47a4-11e8-8738-95627bb24d8a.png)

**Comment by klecuyer** [comment]
@markwooff @LemieuxGen 
I was able to test and can confirm that the username registration still appears in English-only when user is set to login with French settings:
![image](https://user-images.githubusercontent.com/29754185/39191895-ec6aa3ba-47a5-11e8-959c-666f19cf9ade.png)

**Comment by markwooff** [comment]
Unfortunately I'm not able to change the text for the **Register Username** screen so that it would be bilingual. RocketChat actually already contains French text for this screen (and many others) but is only shown when a user logs in, goes to their user preferences and then sets their language to French.

Obviously this causes issues for users that haven't logged in yet and are wanting to see French text. There is an option to set a default language in RocketChat which is currently set to English.. changing this to French may introduce more issues however.

**Comment by klecuyer** [comment]
@markwooff is it something we could ourselves ever enhance in rocket chat eventually, or is it a hard-no, encoded into the way we use rocket chat?

**Comment by markwooff** [comment]
This is definitely an enhancement that we could contribute back to the RocketChat community, but it's not a small task unfortunately.

**Comment by ethanWallace** [comment]
@klecuyer @LemieuxGen I'm going to close this issue because the bilingual changes that can be done have been made. If we want to keep track of the enhancement part of this issue, a separate issue with more details can be made.
