### ISSUE TITLE
Update links to Help content in GCcollab footer

### ISSUE THREAD

**Issue by MGoodberry** [gctools-outilsgc/gccollab#315]
Please update links in GCcollab footer to the following: 
Frequently asked questions - link to: https://gccollab.ca/help/knowledgebase
Help / Contact Us - link to: https://gccollab.ca/help/knowledgebase

Remove link to Tutorials.

**Comment by JOutram77** [comment]
It's just an idea but what if we kept the 'FAQs' in the footer but link it to the FreshDesk. 

Users know what FAQs are but may not know to look for them by clicking on either 'Help/Contact Us' and the 'Feedback' buttons - both of which link to FreshDesk. To assist our decision on this, do we have the stats for then number of times 'FAQs' has been clicked on? Thoughts?

![image](https://user-images.githubusercontent.com/22943228/38749763-d14674b6-3f20-11e8-988f-731eaf92a561.png)

**Comment by LemieuxGen** [comment]
@JOutram77 thanks for the input. I updated the description to reflect the decision to keep FAQs but link it to the Help page. We'll remove Tutorials instead.
