### ISSUE TITLE
Add 2 new mechanisms to Career Marketplace platform

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gccollab#318]
As you may know, the Career Marketplace (formerly known as the Opportunities Platfrom) has been re-branded. As part of our re-brand, we would also like to add two new opportunity types on to GCcollab: 

- Skill sharing / Partage des habiletés 

- Interchange Canada / Échanges Canada

**Comment by markwooff** [comment]
Where would you want these to appear on the current opt-in screen?

![image](https://user-images.githubusercontent.com/5591488/38884608-171546e6-423e-11e8-852d-f17af28216cc.png)

Also, would these follow the same logic as Mentoring and Collaboration opportunities where the group and level fields are disabled when creating a new one?

**Comment by Eldoraaoun** [comment]
Skill Sharing is a development opportunity, Interchange Canada is a Career Opportunity. 
Group and Level is disabled for Skill Sharing - however, enabled for Interchange. 

Thank you!! :)

**Comment by markwooff** [comment]
Okay great, I've set up the two new opportunity types on our dev site. Please have a look at https://dev.gccollab.ca to ensure everything is as it's supposed to be!

**Comment by markwooff** [comment]
@Eldoraaoun have you had a chance to review these changes yet?

**Comment by markwooff** [comment]
Approved by Farah as @Eldoraaoun is on vacation 👍
