### ISSUE TITLE
Cannot reset password

### ISSUE THREAD

**Issue by pabrams** [gctools-outilsgc/gccollab#319]
I tried to reset my password.  I received an email with a link.  The email said "You have requested a new password. Please follow this link to set a new password."

When I click the link, it brings me to a page that says "Reset password", and I can see labels like "New Password" and "Confirm password", but there is nowhere to type any password.  

I'm using IE11  (Edit:  but it happens in Chrome, too)

**Comment by markwooff** [comment]
Hi @pabrams - sorry to hear this. You should be seeing a page that looks like this:

![image](https://user-images.githubusercontent.com/5591488/38893731-2ef533be-4259-11e8-83a4-a0814cce5083.png)

You're saying that you are unable to see the input fields for the passwords on IE11?

**Comment by markwooff** [comment]
Tested on IE11 without issue. Curious if you could post a screenshot of what you're seeing?

**Comment by pabrams** [comment]
Sure:

![image](https://user-images.githubusercontent.com/1376688/38996587-8554443c-43b9-11e8-84c8-bbba6c505cce.png)

![image](https://user-images.githubusercontent.com/1376688/38996648-a3524f92-43b9-11e8-90ea-e5e730c2a2e3.png)

![image](https://user-images.githubusercontent.com/1376688/38996704-c4cf87d4-43b9-11e8-9df0-832a113bdbe1.png)

![image](https://user-images.githubusercontent.com/1376688/38996785-ee66c9f4-43b9-11e8-92dd-ab85a0eca368.png)

![image](https://user-images.githubusercontent.com/1376688/38996974-53b8e800-43ba-11e8-99c7-bdfeecf48875.png)

**Comment by pabrams** [comment]
Same thing in Chrome - sorry if I implied it was IE only.

![image](https://user-images.githubusercontent.com/1376688/38997196-ea141b1c-43ba-11e8-9410-21126bed206e.png)

**Comment by markwooff** [comment]
Thanks for the info, seems that the issue is that the reset link you were sent has expired - however this is not very clear on the user's end. If you request a new password reset, you should be able to use the form. We'll work on adding some information to let the user know the link has expired.

**Comment by LemieuxGen** [comment]
New text for password reset when the link has expired: 

Your password reset link has expired. Request a new password reset to receive a new link by email. 
Button: Reset my password

Votre lien de réinitialisation du mot de passe a expiré. Demander une nouvelle réinitialisation de mot de passe pour recevoir un nouveau lien par courriel.
Bouton : Réinitialiser mon mot de passe

**Comment by markwooff** [comment]
Thanks @LemieuxGen - new messaging is now in!

**Comment by markwooff** [comment]
@pabrams were you able to reset your password now that this change has been made?

**Comment by pabrams** [comment]
@markwooff I was already able to reset using the workaround.  However, i went back to my original email and clicked the expired link, and now I get a nice"your password reset link has expired" instead of that other weirdness.  Looks good!
