### ISSUE TITLE
Notification defaults

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#32]
Can we make notification defaults for all users of GCcollab, 'Email On' for everything (message, group, likes, etc.)??

**Comment by markwooff** [comment]
This can definitely be done, but to do it quickly would require changing some of the core Elgg files. Would be better practice to build a small plugin to add this functionality, however it will take more time.

**Comment by ToferC** [comment]
Recommend that the GCconnex notifications are ported over and that the upcoming notifications digest is completed and tested on GCconnex, then ported over.  Then we can revisit notification settings for GCcollab.  Thanks!

**Comment by markwooff** [comment]
Just an update on this issue.. the latest notifications panel was pulled in from GCconnex and is currently in use on GCcollab. By default, a user is subscribed to a Group's **email** and **site** notifications after joining a Group. The user will see this from their Notifications settings:

![image](https://cloud.githubusercontent.com/assets/5591488/23322715/3e7e6164-fab3-11e6-933b-b44dede44a5d.png)

However a new user will have their Personal Notifications set to **off** by default, should this be changed to **on**? See screenshot below:

![image](https://cloud.githubusercontent.com/assets/5591488/23322734/5197f6f2-fab3-11e6-9165-d5d19a713704.png)

**Comment by ToferC** [comment]
Please default to on. Thanks!

**Comment by markwooff** [comment]
The functionality to set Personal Notifications to "on" by default has been added with 9ab8802addc527aa782b640261327d1c88976346 but I would like to discuss with GCconnex team how these checkboxes are used. Seems that I still receive emails even when unchecked.

**Comment by ToferC** [comment]
Sounds good. We could use more eyes on notification functionality.
