### ISSUE TITLE
User gets Fatal Error every time when accessing GCcollab

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#320]
This user repeatedly gets the following error when logging into GCcollab through the single account service:
![image](https://user-images.githubusercontent.com/29754185/38944485-fce34fa6-4301-11e8-941d-98519f2a0e04.png)

I have tested this, reset the user's password, with no luck. The user can log into the account service and access the wiki, but when clicking GCcollab, gets this error every time.

Email: alison.kinsman@agr.gc.ca

https://support.gctools-outilsgc.ca/helpdesk/tickets/3124

**Comment by markwooff** [comment]
Just made a quick change in the DB so she should be able to login now. First time seeing this, hopefully just a one-off.

**Comment by KevinChagnon** [comment]
Here is another user with the same issue:

E-mail: Jacqueline.Bernauer@canada.ca

Single Sign-on account Active
GCcollab account created but not validated - not in list of unvalidated users in GCcollab admin panel

https://support.gctools-outilsgc.ca/helpdesk/tickets/3158

Is this the same issue?

Other users were able to successfully register/validate before and after this users request.

**Comment by KevinChagnon** [comment]
@markwooff @klecuyer @LemieuxGen

**Comment by markwooff** [comment]
How was her GCcollab account created? Was it created before we implemented the single sign-on? Regardless, her account should be good to go on GCcollab now, just trying to figure out how it was created so we can prevent this going forward. Thanks

**Comment by KevinChagnon** [comment]
As per Collab stats: Member since: | Tue, 03 Oct 2017 12:50:17 -0400
https://gccollab.ca/settings/statistics/Jacqueline.Bernauer

I will inform the user that she should now be able to log in.

Feel free to adjust the status of the ticket as you find fit.

**Comment by markwooff** [comment]
So this is a very particular case where a user created a GCcollab account in the past, never activated it or logged in, and is now trying to log in for the first time using the Single Sign-On. Not sure how many cases like this will exist but if it becomes cumbersome, we can build something to prevent it.

**Comment by KevinChagnon** [comment]
Closing ticket.  Will re-open for further investigation if more issues like this arise.
