### ISSUE TITLE
Remove "Who can register" from the GCcollab splash page

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gccollab#322]
on the GCcollab splash page, please remove the links to the "Who can register" and "Qui peut s'enregistrer". 

This information has been moved to the Terms and Conditions of Use, and should not appear on the splash page according to the [Technical specifications for the Web and mobile presence](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/federal-identity-program/technical-specifications/web-mobile-presence.html#Section3)

**Comment by markwooff** [comment]
The temporary "Who can register" and "Qui peut s'enregistrer" text has now been removed.

**Comment by LemieuxGen** [comment]
Thanks @markwooff !
