### ISSUE TITLE
Add Message icon/link to GCCollab header for navigation between apps

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gccollab#325]
Add icon and link to GCcollab Message on the GCcollab header, to allow users to navigate to Message.
@MPM9000 please add graphic here. Thanks!

**Comment by MPM9000-zz** [comment]
Icon available. If someone could add link.

![mini_message_icon](https://user-images.githubusercontent.com/36711228/39427449-bc973dd2-4c51-11e8-96d2-ea8baafaf149.png)
