### ISSUE TITLE
French blog content not saving

### ISSUE THREAD

**Issue by smellems** [gctools-outilsgc/gccollab#33]
I posted a new blog on GCcollab, but the French version did not save.

https://gccollab.ca/blog/view/7873/gccollab-and-gcconnex-development-environment

## Steps to reproduce
* Create a new blog post
* Add content (title, description, ..) in English and French
* Publish the blog
* Switch the site to French (blog will stay in English)
* Edit the blog (French content is empty)

**Comment by markwooff** [comment]
The working files for GCcollab are a little behind some of the fixes that were done to GCconnex. Will need to pull in these changes to fix this issue with the Blog content not saving in French.

**Comment by Phanoix** [comment]
I'm working on merging GCconnex fixes, etc. into GCcollab, I'll have a pull request for it up soon after the update with the last bit of changes from last year so that I can get those in as well.

**Comment by sdkibb** [comment]
Thanks @Phanoix I've also started a label to bring changes the other way. Particularly around mobile view fixes. I figure this is the best way for now but if you'd prefer another way LMK:

https://github.com/tbs-sct/GCcollab/labels/GCcollabToGCconnexPort

**Comment by markwooff** [comment]
Closing issue as this was addressed as part of the GCconnex pull of bug fixes.
