### ISSUE TITLE
Polls results not showing accurate number of votes

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gccollab#330]
Polls results not showing accurate number of votes.
Example: https://gccollab.ca/polls/view/720564/which-of-the-following-does-your-department-consider-to-be-the-top-priority-lequel-des-elements-suivants-votre-ministere-considere-t-il-comme-la-priorite
Activity shows 13 people have voted.result page still only shows 2
![image](https://user-images.githubusercontent.com/23527358/40184524-7ee64580-59be-11e8-9c2c-052211b0eb24.png)

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gccollab-help/issues/30

**Comment by Phanoix** [comment]
I think that one might have been deleted and a couple similar ones and other recent ones I see don't have this issue, so I can't really replicate it. Is this still an issue?

**Comment by klecuyer** [comment]
@Phanoix Thank you. The user deleted this poll. Any test polls seem to be giving correct results.

One issue remains however, just in editing a poll. https://gccollab.ca/polls/view/705079/choose-your-departments-top-priority-from-among-the-following

As a user, I need to be able to change the title of my poll after I've created it. In the following example, the user has edited the poll title to add the word 'second' 'Choose your Department's **second** top priority from among the following'
On the poll page, the title displays in two places, one has the edit and one doesn't.
![image](https://user-images.githubusercontent.com/29754185/40720683-8b2755f6-63e5-11e8-8af2-aeaec1e42c1e.png)

In the 'preview' page listing all polls, the title is not changed. The poll in this screenshot (created 12:14) should include the word 'second'. 
![image](https://user-images.githubusercontent.com/29754185/40720780-dc0fe9e2-63e5-11e8-8cc3-b3589dc9bfd1.png)

When I go to edit the page, I can see that the change has been saved, but does not appear correctly in every case.
![image](https://user-images.githubusercontent.com/29754185/40720847-0a52f04c-63e6-11e8-847b-21d0c9e6886f.png)

**Comment by Phanoix** [comment]
I think I see what's happening here, the polls mod is build in... several odd ways, one of which is a poll question / title mix.
