### ISSUE TITLE
Label for "Brief group description" in French says "Brief English Description"

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gccollab#335]
When editing the French language section of a group, the field description for "Brief" description says "Brief Description in English" but should say "Brief Description in French".

**Comment by klecuyer** [comment]
Not a bug, just depends on the user's language settings (top toggle)
![image](https://user-images.githubusercontent.com/29754185/40501564-3937555e-5f56-11e8-8973-5c9b32403908.png)
