### ISSUE TITLE
GCcollab search giving 0 results

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#336]
For multiple users I search by name, I get 0 results in the main search:

![image](https://user-images.githubusercontent.com/29754185/40666935-e7de023e-632e-11e8-9085-55159febcf34.png)
![image](https://user-images.githubusercontent.com/29754185/40666960-f325ebd4-632e-11e8-8490-463973ab16d9.png)

They also no not appear in the member search: 
![image](https://user-images.githubusercontent.com/29754185/40667007-0f6bfe5a-632f-11e8-9724-09f18cb06fc0.png)
![image](https://user-images.githubusercontent.com/29754185/40667018-18c6ee88-632f-11e8-9fdd-4f673dd7afc7.png)

Other names forwarded from user: Sheilagh McDermott and Heather Mackeen
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/3738

**Comment by klecuyer** [comment]
@4rsood any ideas?

**Comment by klecuyer** [comment]
This user reports getting 0 results for every search: https://gccollab.ca/profile/Justin.Patrick

@4rsood is there anything we can manually do to fix his search? He's active on the platform and other colleagues (including myself) have a working search feature, but he repeatedly reports 0 results.
![image](https://user-images.githubusercontent.com/29754185/41479136-2c7b220c-7098-11e8-8b4b-c64de3f57360.png)

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/3990

**Comment by pandurx** [comment]
@klecuyer 
I will upgrade Solr engine to the current, then make some minor adjustments on how the results will be displayed on gccollab

**Comment by 4rsood** [comment]
GCcollab search is working now.  It required re-indexing of the site.
