### ISSUE TITLE
Add in Full Screen View for the Chat windows

### ISSUE THREAD

**Issue by killerrin** [gctools-outilsgc/gccollab#338]
A couple of my colleagues and I were wondering

Would it be possible for us to get a full screen view for the Chat Windows? or alternatively, a view that was larger? As it currently is, everything feels claustrophobic and crammed into the small space.

**Comment by Troy-Lawson** [comment]
assuming this issue is for cometchat. cometchat is not being developed actively. we are only supporting it to keep it working, while experimenting with alternative systems (ie: message.gccollab.ca). closing this issue
