### ISSUE TITLE
Registration: Union of Taxation Employees

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#339]
Email: @ute-sei.org
Union of Taxation Employees

https://www.ute-sei.org/en

User story: "I'm working on a co-creation project with a couple of unions (bargaining agents) at the Canada Revenue Agency and I was wondering if employees from the Union of Taxation Employees (domain name: @ute-sei.org) can create a GCcollab account.
 
If not, what would be the procedure to have the union whitelisted?"

@JOutram77

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/3831

**Comment by klecuyer** [comment]
@JOutram77 thoughts?

**Comment by JOutram77** [comment]
I have follow-up with the user on this issue and it has been resolved. We will not be whitelisting unions at this time. The user will instead invite the colleagues they need to work with.
