### ISSUE TITLE
Group members gives fatal error: memory size

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#340]
Clicking on group members gives a fatal error: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4 bytes) in /var/www/html/gccollab/engine/classes/Elgg/Database.php on line 0

Here's the group: https://gccollab.ca/groups/profile/85014/enthe-policy-communityfrla-communautu00e9-des-politiques

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4005

**Comment by Troy-Lawson** [comment]
possible related to pr gctools-outilsgc/gcconnex#1739 ?

**Comment by Troy-Lawson** [comment]
@pandurx was this finished before you left?
