### ISSUE TITLE
Users cannot add group owner/operators: You do not have persmission

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#345]
I cannot recreate this error.

As a group owner, I want to assign a new group operator. This person is already a member of the group. When I select them and click Make operator, I'm told I do not have permissions to do this.

I can confirm multiple users have been reporting this over the past few months. Every time I test and I cannot recreate it. I can add a group owner/operator as an admin, as an admin logged into the owner's account, and on my own personal non-admin account in groups I own.

One group where this was just reported: https://gccollab.ca/groups/profile/595477/canadian-cubesat-project

**Comment by ethanWallace** [comment]
@klecuyer Would it be possible to contact the user who submitted the ticket and ask for a screenshot of how they have the "Add another operator" form filled out before they click the "Make operator" button? If not just what they write exactly in the "Add another operator" field.
