### ISSUE TITLE
Registration: Maersk Line Canada

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#346]
Maersk Line is a multinational company (Ocean vessel operator) doing business in many countries including Canada and the US. I represent Maersk Line Canada for all CBSA compliance issues. 
Email: maersk.com
https://www.maerskline.com/countries/canada

https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4004

**Comment by klecuyer** [comment]
@JOutram77

**Comment by JOutram77** [comment]
With Maersk being a private sector company, I don't believe we are able to whitelist them at this point in time.

**Comment by JOutram77** [comment]
This organization has been added to the domain manager.
