### ISSUE TITLE
File types not being accepted by GCcollab

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#350]
The following file types were added in the admin side of GCcollab but the users are unable to upload them: 
.AI
.XD 
.SVG

**Comment by ethanWallace** [comment]
@JOutram77 Would you be able to try and upload these file types again?

**Comment by JOutram77** [comment]
@ethanWallace I just tried to upload an .AI file and it seemed to work fine. 

@s-duffey I don't have any .XD or .SVG files. Can you try and upload example files in GCcollab sandbox group and let Ethan know if you have success?

**Comment by ethanWallace** [comment]
Seems the issue was probably caused by the old file list still being cached in the file type validation. Users can now upload these file types.
