### ISSUE TITLE
Enable Visio & Microsoft Project files (VSD, VSDX, MPP, MPPX)

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#352]
Looking for a green light to enable Visio files on GCcollab (VSD and VSDX file types)

Is this still done through the GCcollab admin panel?

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4265

**Comment by klecuyer** [comment]
Also mpp, mppx

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4446

**Comment by Phanoix** [comment]
It should still be in the same place in the admin panel, yes.
