### ISSUE TITLE
Registration: Various Indigenous Groups

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#358]
**@afn.ca (Congress of Aboriginal Peoples)
@abo-peoples.org (Congrès des peuples autochtones)
@nwac.ca (Association des femmes autochtones du Canada)
@inuitcircumpolar.com (Inuit Circumpolar Council Canada)
@itk.ca (Inuit Tapiriit Kanatami)
@metisnation.ca (Métis National Council)**

@JOutram77 

https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4418

**Comment by JOutram77** [comment]
These organizations have been added to the domain manager.
