### ISSUE TITLE
Profike More dropdown not showing in mobile

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#36]
It appears to be off screen on my android.

**Comment by markwooff** [comment]
Sorry, which dropdown are you referring to @sdkibb ?

**Comment by sdkibb** [comment]
Profile more menu.

**Comment by sdkibb** [comment]
To test go to your profile, then mobile view in chrome and select Galaxy S5, then click the "More" link. Looks like it's the .dropdown-menu.pull-right -> right: 0; that's doing it. I removed that in 83fc7bcd842884a5b10f49900f4616db4fd9a757 but the right is required to line up the popup to the anchor so it ruins the other popups that are right aligned.

**Comment by markwooff** [comment]
Should be fixed with latest 50a9df1001f92fb61a547b5d9975f7130f407518 commit. Changed the pull direction on that menu item type.

**Comment by sdkibb** [comment]
I just did the exact same thing. OK, commit that to main branch when ready.

**Comment by markwooff** [comment]
Great minds! Alright done and pushed to prod with c8014b41e182837551e446cd5c1b5348483b3c4d.

**Comment by sdkibb** [comment]
Particularly on mobile fixes, let's start putting the GCCollabToGCconnexPort label so Ilia can go through each at a later date. Closed!

#TwoGeeksOnAFridayNight
