### ISSUE TITLE
Wire does not function correctly - Replying and Sharing

### ISSUE THREAD

**Issue by MGoodberry** [gctools-outilsgc/gccollab#364]
When the user clicks "reply", "share" or "who shared this" they receive this error:

![image](https://user-images.githubusercontent.com/35609738/43900057-bbf90734-9bb1-11e8-8fcd-1b6c30b5a780.png)

I am unable to replicate this error, but it happens to the user every time.

**Comment by Troy-Lawson** [comment]
related to the language toggle.
