### ISSUE TITLE
Group description doesn't update

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gccollab#366]
When entering a group description in the "long description" field, after saving and publishing, the updated information doesn't appear on the group description when on the "about" page of a group.
Sometimes, immediately making the chance a second time, saving and publishing, updates the description, but not always.

**Comment by Phanoix** [comment]
Updates show up properly now.

**Comment by PhilAndrecheck** [comment]
Thanks @Phanoix !
