### ISSUE TITLE
Cover image doesn't display in Chrome, only IE

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#373]
This group: https://gccollab.ca/groups/profile/449756/encanadas-platform-for-disaster-risk-reductionfrplate-forme-nationale-pour-la-ru00e9duction-des-risques-de-catastrophe

The cover image/ group banner only displays in IE but not in Chrome. The user experienced this, as did I.
![image](https://user-images.githubusercontent.com/29754185/44727924-2dd61580-aaa9-11e8-87ab-ea1c9e2477d7.png)

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4904

**Comment by Phanoix** [comment]
Tried this from home and it works in chrome and firefox, which makes me conclude that it's more of an internally provided version / configuration of chrome that's the issue.

**Comment by klecuyer** [comment]
User uploaded a jpg version of the photo and the problem is solved
