### ISSUE TITLE
500 Error when user registers new account

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gccollab#375]
Users are getting a server error as soon as they click on **Register**:

![image](https://user-images.githubusercontent.com/42844328/44874290-b5b64e00-ac68-11e8-885a-b9b01a8a5aac.png)

Error message:
![image](https://user-images.githubusercontent.com/42844328/44874320-d1b9ef80-ac68-11e8-9803-c8828c0f95d4.png)

**Comment by marc-donofrio** [comment]
Reported by 3 users and I get the same error:
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4938
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4939
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4940
I was also got the errror in Safari on my phone with the TBS WIFI and my personal mobile network.

**Comment by klecuyer** [comment]
This isn't consistent in every case but we have been able to replicate and has been reported by multiple users this afternoon.

**Comment by Phanoix** [comment]
looks like it was a malformed entry in the email whitelist, fixed it and it's working for me now.
