### ISSUE TITLE
Title Issue with "Ideas" Settings

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gccollab#376]
There is a language/title error when opening the ideas settings. 
![a-dcd-ideas-setting](https://user-images.githubusercontent.com/15625062/44923727-fb712600-acfd-11e8-8b59-7c4060b0faa8.PNG)

**Comment by Phanoix** [comment]
Looks like it might be a spot we missed and it just needs to have the title passed through the language decoding / fetching function.
