### ISSUE TITLE
Group owners cannot remove group members

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gccollab#379]
As a group owner/operator, I should have the ability to remove members of a group.

Currently, if I'm looking at the list of group members, I see the option to Remove member, but when I click it, I get this notice:
![image](https://user-images.githubusercontent.com/29754185/45308859-71d90980-b4f0-11e8-9006-cce1bbdde12c.png)

This was reported by a user and I'm able to replicate the issue myself.

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5005

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5010

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5023

**Comment by klecuyer** [comment]
I also cannot remove group members as an admin.

**Comment by klecuyer** [comment]
@LemieuxGen @Troy-Lawson for next legacy sprint

**Comment by marc-donofrio** [comment]
Here is another one related: https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5075

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5083

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5086

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5103
