### ISSUE TITLE
Registration form - departments not sorted alphabetically

### ISSUE THREAD

**Issue by markwooff** [gctools-outilsgc/gccollab#41]
![image](https://cloud.githubusercontent.com/assets/5591488/21821378/539970ba-d741-11e6-9a6c-500535165bc3.png)

**Comment by JOutram77** [comment]
I'm working on this registration redesign. I'll get a layout to your gents soon.

**Comment by markwooff** [comment]
New registration form has been added to GCcollab with f4d6d8049538a75c6ca9cc7da7877d06878f3dee. Closing issue.
