### ISSUE TITLE
Option to disable the auto-generated email when creating a user account

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#42]

**Comment by ToferC** [comment]
Sorry about that. Hit wrong button. Q: is this priority item and is it applicable to GCconnex and core Elgg?

**Comment by sdkibb** [comment]
Based on a scale of ease of implementation and usefulness it was ranked high. This is big for GCcollab. Fully functional for GCconne. I will add the tag so Ilia can decide. Could be core Elgg worthy, will discuss.

**Comment by markwooff** [comment]
I've actually added this feature in this morning in a separate issue which has already been closed: https://github.com/tbs-sct/GCcollab/issues/39

As simple as adding a checkbox to the backend with the option to enable/disable the emailer:

![image](https://cloud.githubusercontent.com/assets/5591488/21828853/d546b9fa-d760-11e6-8f29-f668b3380420.png)

**Comment by JOutram77** [comment]
This is an issue I put forward to support my work with PCO for the PM's Youth Council.

**Comment by ToferC** [comment]
Understood. Coding changes to accommodate a very small group should be evaluated carefully. We shouldn't be manually adding users as a general practice.

**Comment by ToferC** [comment]
Issue closed as per @markwooff comment above.
