### ISSUE TITLE
Move the input fields of the domain manager from the bottom to the top of the page.

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#43]

**Comment by markwooff** [comment]
Is this referring to the "Add new extension" input box in the admin backend? (see screenshot)

![image](https://cloud.githubusercontent.com/assets/5591488/21830771/1ae57d00-d76d-11e6-8478-bc62e9795bcf.png)

**Comment by JOutram77** [comment]
Yes, exactly. This is not a high priority, but more of a design enhancement. Having to scroll to the bottom of that page to enter additional extensions after a few hundred extensions have been added is quite burdensome.

**Comment by markwooff** [comment]
@JOutram77 definitely understand how cumbersome this could be with the eventual growth of this list. I've gone ahead and moved the input fields to the top of the page within the Domain Manager.

I've also set the table to be displayed in alphabetical order by default. You can also now do both a **SORT** and a **FILTER** where as before you could only do one or the other. Your selection will also be displayed as bold & underlined so you know what sort/filter you are viewing 👍
