### ISSUE TITLE
More QC gov. email extensions to add

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#45]
Sorry, typing mistake... See below.

**Comment by ghost** [comment]
More Quebec gov. organizations email extensions to add:

amt.qc.ca
assnat.qc.ca
banq.qc.ca
bingos-quebec.com
bnq.qc.ca
bonjourquebec.com
casinosduquebec.com
ccq.org
cdpdj.qc.ca
cefrio.qc.ca
cfai.qc.ca
commissairelobby.qc.ca
congresmtl.com
conseil-des-aines.qc.ca
convention.qc.ca
courdappelduquebec.ca
criq.qc.ca
csj.qc.ca
csst.qc.ca
educaloi.qc.ca
electionsquebec.qc.ca
electionsquebec.qc.ca
emploiquebec.net
fadq.qc.ca
fadqdi.qc.ca
fondationdelafaune.qc.ca
grandtheatre.qc.ca
hema-quebec.qc.ca
hydroquebec.com
inesss.qc.ca
innovatechquebec.com
inspq.qc.ca
institutsmq.qc.ca
investquebec.com
ireq.ca
irsst.qc.ca
ithq.qc.ca
lacaisse.com
lautorite.qc.ca
loto-quebec.com
lotoquebec.com
macm.org
mcq.org
mnba.qc.ca
ofqj.org
oqwbj.org
osrcpc.ca
pda.qc.ca
protecteurducitoyen.qc.ca
rcq.qc.ca
regie-energie.qc.ca
revenuquebec.ca
saq.com
sepaq.com
sgfqc.com
sopfeu.qc.ca
sopfim.qc.ca
soquij.qc.ca
spipb.com
table-metropolitaine.org
telequebec.tv
tribunaux.qc.ca
urgences-sante.qc.ca

And thanks to Martin Trudel (CSPQ) for sharing an exhaustive list of QC gov. organizations as well!

**Comment by markwooff** [comment]
@JOutram77 would it make sense to wildcard the *.qc.ca email extension here?

**Comment by ghost** [comment]
FYI, some *.qc.ca websites are not government organizations at all. The subdomain used to be widely available but it is no longer the case. Non-gov. *.qc.ca previous owners can still keep them.

**Comment by markwooff** [comment]
Right, I remember that being mentioned in the last thread. Just thinking of a possible solution to add these email extensions without having to manually enter them one-by-one...

There's a nice list of gov email extensions [here](https://raw.githubusercontent.com/benbalter/gman/master/config/domains.txt) that we might leverage in our system as well.

**Comment by ghost** [comment]
I just tried to register with a few listed email extensions and it doesn't work. @markwooff, has it been pushed to prod?

**Comment by markwooff** [comment]
Sorry @gabrielcossette-ca, thought I had previously mentioned our thoughts on these extensions but that might have been in the other email extension issue.

We're still in the process of reviewing each of these extensions so I'll reopen this issue until we come up with a definite answer on them.

**Comment by ToferC** [comment]
Can we close this?

**Comment by sdkibb** [comment]
Yes, Mark put in wildcard functionality into the domain manager.

**Comment by ghost** [comment]
The bug is not fixed. I tried to register with a @amt.qc.ca address (see my list above) and it still says "Invalid email". This issue is not related to the wildcard functionality.

Please reopen :)

**Comment by JOutram77** [comment]
@gabrielcossette-ca would you happen to have the corresponding list of organizations that matches your above list of email extensions?

**Comment by sdkibb** [comment]
It's not being reopened. Is there a reason you want us to put a liquor store domain into GCcollab?

**Comment by ghost** [comment]
@sdkibb, you are referring to Société des alcools du Québec (SAQ)? It is a quebec government corporation, similar to Canada Post for GC. Isn't the intent to allow employees of gov. corporations to register to GCcollab too? Please clarify.

**Comment by sdkibb** [comment]
Like the Beer Store?

**Comment by ghost** [comment]
It's different. It looks like the Beer Store is a private entity while Quebec SAQ is a gov. corporation.

**Comment by sdkibb** [comment]
The Beer Store is essentially owned by the province via a Master Framework Agreement. Although employees are not provincial employees. Are SAQ employees provincial employees? We don't have Canada Post I'm the list either. We are discussing expansion but for now it's provincial and federal eployees along with students and faculty. 

 Just want to make sure we aren't opening this up past what's required and available to maintain at this point in the pilot. Down the line all these groups with likely have access.

**Comment by ghost** [comment]
Ok, thanks for the explanation. If gov. corporations are out of scope for now, let's park this issue for later. I would suggest you keep it open but label it for a future milestone maybe?

But please add at least these two email extensions, which are definitely provincial employees:
- revenuquebec.ca
- assnat.qc.ca

**Comment by sdkibb** [comment]
Will do. Thanks Gabriel. We're going to add this as part of the open access issue that's upcoming.
