### ISSUE TITLE
Add 'Cabinet Office' as a Ministry in Ontario

### ISSUE THREAD

**Issue by jpmckinney** [gctools-outilsgc/gccollab#51]

**Comment by sdkibb** [comment]
Does the cabinet office have a seperate email address?

**Comment by jpmckinney** [comment]
@sdkibb There is a Ministry dropdown when you go to https://gccollab.ca/register and select:

* Occupation: Provincial/Territorial Government
* Province/Territory: Ontario

It doesn't include Cabinet Office.

However, after registration, it seems that this information is thrown out, as I had to re-enter my Occupation and Department on https://gccollab.ca/profile/James.Mckinney

All of the Ontario Public Service has @ontario.ca addresses to my knowledge.

**Comment by sdkibb** [comment]
Right you are James. Thanks for the heads up. We'll have that in in short order.

**Comment by JOutram77** [comment]
I literally just got on to GitHub to add this issue. @sdkibb @markwooff let's add Cabinet Office (Le Bureau du Conseil des ministers) to the drop-down list and close this issue. I'll open a separate issue because this issue seems to have appeared since we re-developed the registration page.

**Comment by trbouma** [comment]
Hey guys, I had a request from the City of Calgary. Can cities be added to the lis too?

**Comment by JOutram77** [comment]
@trbouma I have recorded your request to grant access of GCcollab to Canadian cities. I hope to have a response soon. I'll be sure to let you know.

**Comment by markwooff** [comment]
I've gone ahead and added "Cabinet Office" as an option for the Ontario dropdown of Provincial/Territorial Government.

**Comment by sdkibb** [comment]
If it's in the options for the edit profile as well then we can close this issue.

**Comment by markwooff** [comment]
I centralized the list to one location so that the Registration page and the Edit Profile page share the same dropdown information (in both ENG and FRA). Going forward, I would like to have this list be editable from the backend by an admin but for now it will be easy for a developer to update.

**Comment by jpmckinney** [comment]
The PR works for me, thanks! Feel free to close.
