### ISSUE TITLE
Registration information (occupation, organization) is lost for some users after registration

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#52]
Some users are reporting that after registering for an account and accessing GCcollab, that they have to edit their profile to ensure their info, such as their occupation and organization are reflected correctly. 

The dropdown info in the 'edit profile' fields do not reflect the same info that's listed in the registration page, since we redeveloped the registration page. You may recall that the fields on the registration page were tied to the domain manager plug-in. Since the redesign that is not the case. It turns out that we need to make the same change to the 'edit profile' fields. Perhaps this will resolve the issue of lost content. Any thoughts?

**Comment by markwooff** [comment]
Whoops, didn't mean to close this issue right away. I've been working on the fix for this since Friday, just pushed out the latest code to ensure that the 'Edit Profile' fields are usable with the newly introduced fields.
