### ISSUE TITLE
Error code displayed in the education field of various users.

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#57]
See the following screenshot as an example:

<img width="514" alt="error message - education field" src="https://cloud.githubusercontent.com/assets/22943228/22221894/c77cb262-e182-11e6-9514-970bd65cbde1.PNG">

**Comment by markwooff** [comment]
There was some code in the Onboarding module that would add an Education entry for users even if they hadn't entered anything. The default text for the entry is the ERROR message in your screenshot.

Step 2 of the Onboarding module is only supposed to show the Education inputs for Students/Academics. The code has been updated to do this.
