### ISSUE TITLE
Put the Opportunities Platform on GCcollab

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gccollab#6]
Add Opportunity Platform to GCcollab once bugs fixed and performance optimized.

From tbs-sct/gcconnex#477

@JOutram77  GCcollab has its own home here now, development / adjusting features for GCCollab will happen here too.

**Comment by JOutram77** [comment]
Sorry...i now realize my mistake. Thanks for this.

**Comment by ToferC** [comment]
@Phanoix @JOutram77 - I edited the Issue based on conversations with Jeff.  Migration of OP will occur after we squish the bugs, improve the Find Members Query performance and improve analytics to a usable state.

**Comment by sdkibb** [comment]
@Phanoix are we ready for this now? OCHRO asked for an update.

**Comment by Phanoix** [comment]
It's merged in and on prod now, just need to activate and do some tests to make sure it's all good.

**Comment by sdkibb** [comment]
On GCcollab prod?

**Comment by Phanoix** [comment]
Of course, it went up right after I merged in #15 
It still needs to be activated in the admin side though.

**Comment by sdkibb** [comment]
Nice. OK, we'll get this and the onboarding live and start testing today.

**Comment by Phanoix** [comment]
I'll help test when it's activated.

**Comment by markwooff** [comment]
Should test on [dev](http://gccollabdev.canadaeast.cloudapp.azure.com) first. Spun up a new dev environment VM on Azure the other day.

I will pull these latest changes so it's ready to test.
