### ISSUE TITLE
A group admin (not owner) is unable to upload a banner graphic in the group

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#63]
Mylene Lafleur is a group admin for the Career Boot Camp 2017 group ([https://gccollab.ca/groups/profile/7230/career-boot-camp-2017-camp-de-carrieres-2017]), but is unable to upload a banner graphic to the group. 

Concerned that other group admins having similar issues. 

Note, there is a banner for this group because I uploaded it.

**Comment by sdkibb** [comment]
Can you replicate this on GCconnex?

**Comment by markwooff** [comment]
Just tested this on preprod GCconnex, the bug exists there too. The creator of the group can upload a new cover image but when a Group Operator does this, the image does not get uploaded.

@Phanoix has then been logged on the GCconnex side for bugs?

**Comment by Troy-Lawson** [comment]
relates to https://github.com/gctools-outilsgc/gcconnex/issues/708

**Comment by markwooff** [comment]
Fixed with latest changes from Nick's commit https://github.com/gctools-outilsgc/gcconnex/pull/795/commits/ee24fa9f9d0f56881aa0f261f488e4e9872a1716 .
