### ISSUE TITLE
Allow Any Approved User to Invite Anyone

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#66]
We need a module that will allow any approved user to invite anyone else, even if the domain and/or organization are not in the approved list.

The system should also track who invited who.

**Comment by JOutram77** [comment]
As I've mentioned in the past, perhaps this is a module that we can use from the Elgg platform hosted by Athabasca University in Alberta, called [The Landing](https://landing.athabascau.ca/).

**Comment by ToferC** [comment]
Let's review this from a UX perspective this week. What do we want invitees to see and feel when they get the invitation?

**Comment by markwooff** [comment]
After initial discussion a few days ago, we were thinking to piggyback off of the pre-existing UI available through the [Invite my colleagues](https://gccollab.ca/invite/) module. This would be from the sender's perspective.

The receiver's perspective will need to be discussed further. Do we want to send them a link in an email to the [Register](https://gccollab.ca/register) page? Will this email require new language for this type of registration?

**Comment by sdkibb** [comment]
So we've decided that we will put the inviter's  picture, name and work title in the left column of the registration page to give the invitee a more personal feel/connection when registering.
