### ISSUE TITLE
Create One-Time Profile Nudge

### ISSUE THREAD

**Issue by sdkibb** [gctools-outilsgc/gccollab#68]
In order to get past signups to add to their profile we need to do a single nudge/notification to ask them to fill out more complete information on their profiles. This serves to increase colleague connection suggestions via the suggest algorithm, increases the data value for our stats and allows for better job searching capability when we onboard the opportunity platform for student employment.

**Comment by cyclingzealot** [comment]
Just an update to our conversation, I'm going to work on https://github.com/gctools-outilsgc/gcpedia/issues/27 first.  Feel free to delete this comment.

**Comment by markwooff** [comment]
A quick plugin was created to add this popup/modal reminder for user's to update their profile. An admin can set the reminder time from the Elgg backend:

![image](https://cloud.githubusercontent.com/assets/5591488/24876338/5bdd3942-1df9-11e7-9f65-74d92caf417b.png)

We would just need the appropriate language chosen for the message:

![image](https://cloud.githubusercontent.com/assets/5591488/24876317/422528ca-1df9-11e7-9a29-e350896fc2cf.png)

**Comment by markwooff** [comment]
@JOutram77 maybe you could have a look at the language used for the reminder?

**Comment by markwooff** [comment]
@LemieuxGen @ToferC do you think we could use any changes to the language for this reminder to users? The "**Just Checking In!**" translates to "**Salut, bonjour!**" and the "**Update Profile**" translates to "**Réviser le profil**".

Would still need to have the main paragraph translated.

**Comment by LemieuxGen** [comment]
@markwooff here's the text: 
**Quoi de neuf!**
Nous avons remarqué que vous n'avez pas mis à jour votre profil depuis un moment. Prenez un moment pour mettre à jour vos informations.
Mettre à jour votre profil _(Button)_

Let me know if you have questions.
CC: @ToferC

**Comment by markwooff** [comment]
Awesome, thanks @LemieuxGen !
