### ISSUE TITLE
Bug - Malfunctioning 'Like' timestamps on the Newsfeed

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#7]
In the newsfeed, when someone joins a group, 'likes' may appear but the issue is, the 'likes' pre-date someone joining the group. It seems as those it's displaying the 'likes' of the group that's been joined.

**Comment by ToferC** [comment]
This is a known issue on GCCONNEX. Can you link to the issue on the other
repo? Thanks!

**Comment by Troy-Lawson** [comment]
mouseover message

**Comment by piet0024** [comment]
Currently on production the alt / title text on the icon says "Like this Group"
