### ISSUE TITLE
Ensure the carousel on the home page is accessible.

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#70]
Create separate French and English fields (divs) for the carousel so that text content in a image can be read by screen-readers.

**Comment by markwooff** [comment]
The image carousel currently in use on GCcollab has been enhanced to provide fields where alt text can be provided for images that have text embedded in it. The additional fields can be viewed from the same screen when adding/editing images:

![image](https://cloud.githubusercontent.com/assets/5591488/23313358/5d94507c-fa8b-11e6-8ead-65b70b948996.png)
