### ISSUE TITLE
Filter newsfeed feature bugged / not working

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gccollab#73]
Selecting the filter newsfeed displays content over existing content that is hard to read. It also seems like the filter out colleague connections isn't working.

**Comment by markwooff** [comment]
Thanks for letting me know about this @ToferC, issue has been fixed and the filter option is now visible.

The functionality for the checkbox appears to be working for me, see screenshot below without the box checked:

![image](https://cloud.githubusercontent.com/assets/5591488/22553330/4ec27406-e92a-11e6-8ec2-bd45eb3b74d8.png)

And now with the box checked:

![image](https://cloud.githubusercontent.com/assets/5591488/22553377/77d8b616-e92a-11e6-8950-f87aaabf4b44.png)

Is this not the case with your Newsfeed?
