### ISSUE TITLE
Hide the arrow buttons in the Spotlight Image Carousel widget

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#79]
A number of users have identified the arrows in the Spotlight Image Carousel to be an issue because they block valuable space in the graphics. 

Ideally, the buttons would exist but invisibly. This is a common practice on other carousels/image sliders. A good example is on the CBC website at: [http://www.cbc.ca/news/canada/photos http://www.cbc.ca/news/canada/photos]

<img width="559" alt="carousel image" src="https://cloud.githubusercontent.com/assets/22943228/22666756/eddd11bc-ec87-11e6-9825-238cba88a236.PNG">

**Comment by ToferC** [comment]
Suggest we close this as matter of personal taste. If we remove the tags another user will ask us to re-add them.
