### ISSUE TITLE
Embedded pictures - best practices

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#83]
Question from user - what are the best practices regarding embedded pictures in html.

I have been using the following method:

1. add pictures in the photo album
2. find the hyperlink for the "large" image which does not crop
3. add the URL into the html page

However, this makes all the icons public. Is there another location to store images, possibly as a shared resource?

Find the question at: https://gccollab.ca/groups/profile/11776/gccollab-support-for-group-owners

**Comment by ToferC** [comment]
Closing issue as not requiring developer focus.
