### ISSUE TITLE
Share button not working properly

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gccollab#88]

**Comment by markwooff** [comment]
Hi Joy,

Do you think you could provide some more details on this issue? i.e. where you clicked the button from, what happened after clicking, etc. Screenshots are more than welcome!

**Comment by ToferC** [comment]
@joymosk - please include a user story and additional context as requested or close this issue. Thanks!

**Comment by markwooff** [comment]
Bumping.. @joymosk

**Comment by sdkibb** [comment]
Lack of information.
