### ISSUE TITLE
Edit profile field small

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#90]
Under 'Edit Profile' the website field is strangely smaller than the other fields. See the following screenshot as an example

<img width="486" alt="screenshot - bug" src="https://cloud.githubusercontent.com/assets/22943228/23327174/8461b858-fad5-11e6-98fc-d00769bc7cf7.PNG">

**Comment by markwooff** [comment]
You mentioned this today but I'm not sure which page this is from since the main Edit Profile is a modal pop-up when clicking Edit from the user's profile page (i.e. https://gccollab.ca/profile/Jeffrey.Outram). Is this screenshot from another area?

**Comment by JOutram77** [comment]
Click on your user profile picture at the top right, then click on "My Profile" and then "Edit". 

Once on that page, scroll to the bottom to see the field I mentioned.

**Comment by markwooff** [comment]
Right, that's what I thought but I'm not seeing that from my profile:

![image](https://cloud.githubusercontent.com/assets/5591488/23327635/67eb0fdc-fadd-11e6-835d-06dec6e4a2eb.png)

I'll try viewing from a different profile to see if I can replicate the bug.

**Comment by markwooff** [comment]
I've found the page you were referring to, I imagine it is the "old" Edit Profile page which was replaced with the popup version containing additional fields. It can be accessible by using the link format of https://gccollab.ca/profile/USER.NAME/edit

I'm just wondering whether this older edit screen should even be accessible, and if it is still accessible on GCconnex?

**Comment by ToferC** [comment]
Probably not - but I'd consider this a minor issue. If we can 404 or redirect quickly, then let's do it.  Otherwise just close as long as our links point to the correct pop-up interface.

**Comment by markwooff** [comment]
Most links to the Edit Profile page should be pointing to the latest, but I've placed in a redirect just in case. Closing issue.
