### ISSUE TITLE
There is a bug with symbols coming up as various characters

### ISSUE THREAD

**Issue by JOutram77** [gctools-outilsgc/gccollab#93]
<img width="526" alt="gccollab screenshot" src="https://cloud.githubusercontent.com/assets/22943228/23379926/c941050e-fd06-11e6-8cad-b8a3a3784125.PNG">

**Comment by ToferC** [comment]
This has been addressed in GCconnex.

**Comment by markwooff** [comment]
Great, this will be part of the next code pull from GCconnex.
