### ISSUE TITLE
unable to join group or share from group on mobile touch Chrime/Firefox

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gccollab#97]
Unable to join groups, select member options or share group from group page from Android mobile phone. Tested on Chrome and Firefox with same result. 

Full functionality on desktop in both browsers.

**Comment by markwooff** [comment]
It may be a good idea to do a full overview of GCcollab on mobile to ensure the UX is consistent on all platforms. This is a good place to start!

**Comment by markwooff** [comment]
Join/options/share buttons are now functional on mobile devices from Group page. Closing issue.
