### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by zramsay** [gctools-outilsgc/gccollab#98]
The readme currently provides no information about the project or how to get started contributing/using the tool. My suggestion would be something along the lines of https://gist.github.com/jxson/1784669 and I'm happy to take a stab at it.

**Comment by JOutram77** [comment]
Funny enough I started working on this last night. It will be have to be made available in both English and French so I'll you know when it's up for your review. I'd appreciate any feedback you may have.
Thanks

**Comment by zramsay** [comment]
sounds good.

**Comment by ToferC** [comment]
@joutram77 - could please push whatever you have so far? @zramsay - thanks so much for your offer to help! We'd love your expertise in moving this forward. We can collaborate on the EN text and then we'll get translation ASAP.

**Comment by zramsay** [comment]
cool, I can help with some of the translation

**Comment by JOutram77** [comment]
@zramsay I've posted the English content I prepared. Any feedback or translations you could help with would be greatly appreciated. Thanks again for your offer and support of GCcollab.

**Comment by markwooff** [comment]
I've updated the `INSTALL.md` file with the correct information relative to GCcollab.

**Comment by markwooff** [comment]
`README.md` file was updated by @JOutram77 with 3eaa208d6849b7419f66651619febe697a5262a2. Closing issue.
