### ISSUE TITLE
Mobile application for gc tool kit

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gccollab#99]

**Comment by sdkibb** [comment]
The mobile all is a seperate project and repo. We will make it public probably next week.

**Comment by markwooff** [comment]
Web Preview is up at http://gctools.ca/gctoolkit/ - working on compatibility with IE & Blackberry.

**Comment by markwooff** [comment]
The GCToolkit mobile application is now compatible on IE & Blackberry and is available for download on Android and iOS devices (limited on iOS as we have to approve the devices using the app).

App Download Link: https://build.phonegap.com/apps/2579937/
